"""
Build a slim Falcon seed DB for production bundling.

Source:  universe_engine/data/db/kanida_universe.db (~1.6 GB, has intraday +
         outcomes + validations not used at runtime)
Target:  data/db/kanida_universe.db (slim, ~35 MB, fits in git)

Tables included in the seed:
  - universe_master, falcon_sectors, corp_action_calendar  (small)
  - ohlc_daily, ohlc_weekly                                (~40 MB)
  - falcon_pattern_candidates, falcon_promoted_patterns    (rules, ~1 MB)

Tables EXCLUDED (regenerated by cron jobs after first deploy):
  - falcon_features    → regenerated by daily_features (idempotent)
  - falcon_outcomes    → only needed for offline backtest publishing
  - falcon_pattern_validations → only needed for pattern detail panel
  - ohlc_1min, 5min, 15min, 30min, futures_daily → not used by V7.1

Run once before deploying:
    python universe_engine/scripts/build_falcon_seed.py
"""
import shutil
import sqlite3
import sys
from pathlib import Path


SOURCE = Path(__file__).resolve().parent.parent / "data" / "db" / "kanida_universe.db"
TARGET = Path(__file__).resolve().parent.parent.parent / "data" / "db" / "kanida_universe.db"

# Tables to KEEP wholly. Anything else is dropped.
KEEP = {
    "universe_master",
    "falcon_sectors",
    "corp_action_calendar",
    "ohlc_daily",
    "ohlc_weekly",
    "falcon_pattern_candidates",
    "falcon_promoted_patterns",
    "falcon_features",       # kept but pruned to last 30 days below
    # The 3 runtime tables are recreated by db_init.apply_extensions on app boot
}

# Within these tables, prune older rows to keep image small. The runtime can
# regenerate older rows via daily_features cron if anyone backtests historically.
PRUNE_TO_RECENT_DAYS = {
    "falcon_features": 30,
}


def main():
    if not SOURCE.exists():
        sys.exit(f"Source DB not found: {SOURCE}")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if TARGET.exists():
        print(f"[seed] removing existing target {TARGET}")
        TARGET.unlink()

    print(f"[seed] copying {SOURCE.stat().st_size/1e6:.0f} MB → {TARGET}")
    shutil.copy2(SOURCE, TARGET)

    con = sqlite3.connect(str(TARGET))
    con.execute("PRAGMA foreign_keys = OFF")

    all_tables = [r[0] for r in con.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    )]

    drop_tables = [t for t in all_tables
                    if t not in KEEP and not t.startswith("sqlite_")]
    print(f"[seed] dropping {len(drop_tables)} tables: {drop_tables}")
    for t in drop_tables:
        con.execute(f'DROP TABLE IF EXISTS "{t}"')
    con.commit()

    # Prune large tables to recent rows only
    for tname, ndays in PRUNE_TO_RECENT_DAYS.items():
        latest = con.execute(f'SELECT MAX(trade_date) FROM "{tname}"').fetchone()[0]
        if latest is None: continue
        cutoff = con.execute(
            f"SELECT date(?, '-{ndays} days')", (latest,)
        ).fetchone()[0]
        before = con.execute(f'SELECT COUNT(*) FROM "{tname}"').fetchone()[0]
        con.execute(f'DELETE FROM "{tname}" WHERE trade_date < ?', (cutoff,))
        after = con.execute(f'SELECT COUNT(*) FROM "{tname}"').fetchone()[0]
        print(f"[seed] pruned {tname}: {before:,} → {after:,} (kept {ndays} days, cutoff {cutoff})")
    con.commit()

    print(f"[seed] VACUUM (rebuild + compact)")
    con.execute("VACUUM")
    con.close()

    final_mb = TARGET.stat().st_size / 1e6
    print(f"[seed] DONE. Size: {final_mb:.1f} MB")
    if final_mb >= 100:
        print(f"[seed] WARNING: > 100 MB — exceeds GitHub single-file limit.")
        print(f"        You'll need Git LFS or to drop more tables.")
    else:
        print(f"[seed] ✓ Fits under GitHub's 100 MB single-file limit.")

    con = sqlite3.connect(str(TARGET))
    print("\nFinal table row counts:")
    for t in sorted(KEEP):
        try:
            n = con.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0]
            print(f"  {t:<35s} {n:>12,}")
        except sqlite3.OperationalError:
            print(f"  {t:<35s} (missing)")
    con.close()


if __name__ == "__main__":
    main()
