import React,{useEffect,useState,useRef} from 'react';
import {View,Platform,useWindowDimensions,ActivityIndicator} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import * as Crypto from 'expo-crypto';
import {useAuth,openExternal} from './Auth';
import {useProduct} from './context';
import {api,money,pct,dateTimeText,dateText} from './model';
import {planError} from './ExitPlan';
import {dataAgeDays,dataAgeText,isStale} from './decision';
import {DeskPage} from './TraderDesk';
import {Field,Consent,FormPage} from './AccessScreens';
import {C,T,s,Button,Badge,Empty,Loading,Sheet,Chip,layoutMode} from './ui';
import {usePanelVisible} from './layout/index';
const stamp=(n:number)=>n?dateTimeText(n):'—';
// Readable refusals (EXIT_EVIDENCE, EXIT_EVIDENCE_CHANGED, DATA_STALE, PLAN_REQUIRED; else the server message). Defined in ExitPlan to avoid a PlanReview→PilotScreens import cycle.
export {planError};
// A test order needs a draft whose exact exit rule has tested evidence. Illustrative plans never qualify; legacy plans qualify only when their rule was the frozen tested rule.
const simulatable=(p:any)=>p?.status==='draft'&&p?.illustrative!==true&&p?.tradable_evidence===true;
function Head({title,detail}:any){return <View style={{gap:9}}><T accessibilityRole="header" style={s.title}>{title}</T><T style={{fontSize:16,lineHeight:25,color:C.muted}}>{detail}</T></View>}
function Message({error,notice}:any){return <>{!!error&&<T accessibilityRole="alert" style={{fontSize:14,lineHeight:23,color:C.red}}>{error}</T>}{!!notice&&<T style={{fontSize:14,lineHeight:23,color:C.green}}>{notice}</T>}</>}
function Row({label,value}:any){return <View style={[s.between,{flexWrap:'wrap'}]}><T style={{fontSize:14,color:C.muted}}>{label}</T><T style={{fontSize:15}}>{value}</T></View>}
export function Account(){
 const auth=useAuth(),params=useLocalSearchParams();const [data,setData]=useState<any>(null),[readiness,setReadiness]=useState<any>(null),[error,setError]=useState(params.error?'Broker connection was not completed. Please reconnect.':''),[notice,setNotice]=useState(params.broker?'Kite is connected. Live orders remain disabled.':''),[busy,setBusy]=useState(''),[email,setEmail]=useState(''),[link,setLink]=useState(''),[confirm,setConfirm]=useState('');
 async function refresh(){setData(await api('/api/account'));if(auth.user?.role==='owner')setReadiness(await api('/api/admin/readiness'))}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[auth.user?.id]);
 async function act(key:string,fn:()=>Promise<any>){setBusy(key);setError('');try{await fn();await refresh()}catch(e:any){setError(e.message)}finally{setBusy('');setConfirm('')}}
 async function connect(){if(Platform.OS!=='web'){await openExternal((auth.config.mobile_origin||auth.config.origin)+'/account');setNotice('Complete broker connection in the browser, then refresh this account.');return}const result=await api('/api/broker/kite/start',{});await openExternal(result.url)}
 const sheet:Record<string,string[]>={sessions:['Sign out every device?','You will need to sign in again on the web and mobile app.','Sign out all devices'],disconnect:['Disconnect Kite?','This revokes the stored authorization. It does not close broker positions or cancel existing broker orders.','Disconnect Kite'],
  access:[`Grant pilot access to ${email}?`,`${email} will receive 14 days of included pilot access, starting now, with no payment requested. Check that this is the intended person.`,'Grant 14 days of access'],
  recovery:[`Create a recovery link for ${email}?`,`Any earlier recovery links for ${email} stop working. When this link is used, every signed-in session for that account is revoked. It expires in 30 minutes, and no email is sent; share it privately.`,'Create recovery link']};const current=sheet[confirm]||sheet.disconnect;
 if(!data)return error?<DeskPage><Message error={error}/><Button label="Retry" onPress={()=>refresh().catch(e=>setError(e.message))}/></DeskPage>:<Loading/>;
 return <DeskPage><Head title={`Your workspace, ${data.user.name.split(' ')[0]}.`} detail="One account for your research, broker connection and plans."/><Message error={error} notice={notice}/>
 <View style={s.card}><View style={s.between}><T style={{fontFamily:'InterSemi',fontSize:19}}>Zerodha Kite</T><Badge label={data.broker.status.replace(/_/g,' ').toUpperCase()} tone={data.broker.status==='connected'?'green':'amber'}/></View><T style={{fontSize:15,lineHeight:25,color:C.muted}}>Connect through Kite’s own login. Authorization expires daily; reconnect when prompted. Connecting your account does not enable live orders.</T>{data.broker.account&&<Row label="Connected account" value={data.broker.account}/>}<Row label="Session expires" value={stamp(data.broker.expires)}/><View style={[s.row,{flexWrap:'wrap'}]}><Button label={data.broker.status==='connected'?'Reconnect Kite':'Connect Kite'} disabled={!data.broker.configured||!auth.billing?.access} loading={busy==='connect'} onPress={()=>act('connect',connect)}/><Button label="Refresh status" kind="outline" onPress={()=>act('refresh',refresh)}/>{data.broker.status==='connected'&&<Button label="Disconnect" kind="ghost" onPress={()=>setConfirm('disconnect')}/>}</View>{!auth.billing?.access&&<T style={{color:C.amber}}>Complete billing setup to connect a broker.</T>}{!data.broker.configured&&<T style={{color:C.amber}}>The owner needs to configure the Kite Connect app.</T>}</View>
 <View style={s.card}><T style={{fontFamily:'InterSemi',fontSize:19}}>Your pilot membership</T><Row label="Account" value={data.user.email}/><Row label="Access" value={data.billing.access_reason}/><Row label="Payments" value="Razorpay · test mode"/><Button label="Manage membership" kind="outline" onPress={()=>router.push('/billing')}/></View>
 <View style={s.card}><T style={{fontFamily:'InterSemi',fontSize:19}}>Security & devices</T><Row label="Active sessions" value={data.devices}/><T style={{fontSize:14,lineHeight:23,color:C.muted}}>Signing out of all devices also revokes the mobile app’s session. Broker authorization is managed separately.</T><View style={[s.row,{flexWrap:'wrap'}]}><Button label="Sign out" kind="outline" onPress={()=>act('logout',async()=>{await auth.signOut();router.replace('/welcome')})}/><Button label="Sign out all devices" kind="ghost" onPress={()=>setConfirm('sessions')}/></View></View>
 {readiness&&<View style={s.card}>
  <T style={{fontFamily:'InterSemi',fontSize:19}}>Pilot owner controls</T>
  <T style={{fontSize:14,color:C.muted}}>Invitations are private, single-use and expire in 72 hours. Recovery links expire in 30 minutes and revoke all sessions when used.</T>
  <Field label="Invite or recover an email" value={email} onChangeText={setEmail} keyboardType="email-address"/>
  <View style={[s.row,{flexWrap:'wrap'}]}><Button label="Create invitation" kind="soft" disabled={!email} loading={busy==='invite'} onPress={()=>act('invite',async()=>setLink((await api('/api/admin/invites',{email})).url))}/><Button label="Grant 14 days of pilot access" kind="outline" disabled={!email} loading={busy==='access'} onPress={()=>setConfirm('access')}/><Button label="Create recovery link" kind="outline" disabled={!email} loading={busy==='recovery'} onPress={()=>setConfirm('recovery')}/></View>
  {!!link&&<View style={{gap:8}}><T style={{fontSize:13,color:C.amber}}>Share this link privately with the intended person. No email has been sent.</T><T selectable style={{fontSize:13,lineHeight:23}}>{link}</T></View>}
  <View style={s.line}/>
  {[['Google sign-in',readiness.google],['Razorpay test billing',readiness.razorpay],['Kite credentials',readiness.kite],['Live execution',false]].map(([l,v])=><Row key={String(l)} label={l} value={v?'Configured':l==='Live execution'?'Disabled':'Awaiting setup'}/>)}
  <T style={{fontSize:14,color:C.muted}}>Callback URLs for this environment</T>
  {Object.entries(readiness.callbacks).map(([key,value])=><View key={key} style={{gap:5}}><T style={{fontSize:13,color:C.green}}>{key}</T><T selectable style={{fontSize:13,lineHeight:21}}>{String(value)}</T></View>)}
 </View>}
 <View style={[s.row,{flexWrap:'wrap'}]}><Button label="Pilot terms" kind="ghost" onPress={()=>router.push('/terms')}/><Button label="Privacy" kind="ghost" onPress={()=>router.push('/privacy')}/><Button label="Open on my phone" kind="ghost" onPress={()=>router.push('/connect')}/></View>
 <Sheet visible={!!confirm} onClose={()=>setConfirm('')} title={current[0]}><T style={{fontSize:16,lineHeight:26}}>{current[1]}</T><Button label={current[2]} loading={!!busy} onPress={()=>act(confirm,async()=>{if(confirm==='sessions'){await auth.signOut(true);router.replace('/signin')}else if(confirm==='access'){await api('/api/admin/access',{email});setNotice(`Included pilot access granted to ${email} for 14 days.`)}else if(confirm==='recovery')setLink((await api('/api/admin/recovery',{email})).url);else await api('/api/broker/disconnect',{})})}/></Sheet>
 </DeskPage>
}
export function BillingScreen(){
 const auth=useAuth();const [data,setData]=useState<any>(null),[consent,setConsent]=useState(false),[cancel,setCancel]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setData(await api('/api/billing/status'));await auth.refresh()}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[]);
 async function act(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false);setCancel(false)}}
 return <FormPage title="One membership. Your full workspace." detail="Chart research, personal watchlists, plan review and a virtual workflow account, together."><Message error={error}/><View style={s.card}><Badge label="RAZORPAY TEST MODE" tone="amber"/><T style={{fontFamily:'ManropeBold',fontSize:26}}>Private pilot</T><T style={{fontSize:15,lineHeight:25,color:C.muted}}>Invite-only access. The owner has included access. Other members use the test subscription plan once it is configured. Pricing is shown by Razorpay before authorization.</T><Row label="Your access" value={data?.access_reason||'Loading'}/>{data?.subscription&&<><Row label="Subscription" value={data.subscription.status}/><Row label="Current period ends" value={stamp(data.subscription.current_end)}/>{data.subscription.cancel_at_end&&<T style={{color:C.amber}}>Cancellation is scheduled at the end of the current period.</T>}</>}</View>
 {!data?(error?<Button label="Retry billing status" kind="outline" onPress={()=>{setError('');refresh().catch(e=>setError(e.message))}}/>:<View accessibilityLiveRegion="polite" style={[s.card,s.row]}><ActivityIndicator color={C.green}/><T style={{fontSize:15,color:C.muted}}>Checking checkout setup…</T></View>):!data.configured?<View style={s.card}><T style={{fontSize:17,fontFamily:'InterSemi'}}>Checkout is awaiting setup.</T><T style={{fontSize:15,lineHeight:25,color:C.muted}}>The owner needs a Razorpay test account and subscription plan. No payment has been requested. Your account remains saved.</T></View>:<><Consent value={consent} onChange={setConsent}>I understand this is a Razorpay test subscription. I will use test payment details.</Consent><Button label={data?.subscription?'Continue test checkout':'Open test checkout'} disabled={!consent||!!data?.access} loading={busy} onPress={()=>act(async()=>{const checkout=await api('/api/billing/checkout',{acknowledge_test:true});await openExternal(checkout.url)})}/><Button label="I’ve completed checkout · refresh access" kind="outline" loading={busy} onPress={()=>act(async()=>{await api('/api/billing/refresh',{})})}/></>}
 {data?.subscription&&!data.subscription.cancel_at_end&&<Button label="Cancel test subscription" kind="ghost" onPress={()=>setCancel(true)}/>}<Button label={data?.access?'Open my workspace':'Back to my account'} kind="outline" onPress={()=>router.push(data?.access?'/':'/account')}/><Sheet visible={cancel} onClose={()=>setCancel(false)} title="Cancel this subscription?"><T style={{fontSize:16,lineHeight:26}}>Cancellation is requested for the end of the current billing cycle. Your account and saved plans remain available for later use.</T><Button label="Confirm cancellation" loading={busy} onPress={()=>act(async()=>{await api('/api/billing/cancel',{})})}/></Sheet></FormPage>
}
export function Activity(){const {product,refreshProduct,loading}=useProduct(),[filter,setFilter]=useState('all'),[error,setError]=useState('');const events=(product.events||[]).filter((e:any)=>filter==='all'||e.kind===filter);return <DeskPage><Head title="Every decision has a trail." detail="Your account, research plans and order events in one timeline."/><View style={[s.row,{flexWrap:'wrap'}]}>{['all','plan','simulation','broker','billing','session'].map(v=><Chip key={v} label={v==='all'?'Everything':v[0].toUpperCase()+v.slice(1)} active={filter===v} onPress={()=>setFilter(v)}/>)}<Button label="Refresh" kind="ghost" onPress={()=>refreshProduct().catch((e:any)=>setError(e.message))}/></View><Message error={error}/>{loading&&!(product.events||[]).length?<Loading/>:events.length?events.map((e:any)=><View key={e.id} style={[s.card,{borderLeftColor:e.kind==='simulation'?C.amber:C.green,borderLeftWidth:2}]}><View style={[s.between,{flexWrap:'wrap'}]}><T style={{fontSize:17,fontFamily:'InterSemi'}}>{e.title}</T><T style={{fontSize:12,color:C.muted}}>{stamp(e.created)}</T></View><T style={{fontSize:15,lineHeight:25,color:C.muted}}>{e.detail}</T><T selectable style={{fontSize:12,color:C.muted}}>Reference {e.id.slice(0,12)}</T></View>):<Empty title="Your timeline starts here" detail="Save a setup or make a plan to see the next step recorded here."/>}</DeskPage>}
export function AutoTrade(){
 const {product,refreshProduct,setStudyDraft,loading,state}=useProduct(),{width}=useWindowDimensions();const [refusedStale,setRefusedStale]=useState(false),age=dataAgeDays(state?.source_latest),stale=isStale(age,state?.source_stale)||refusedStale;const [data,setData]=useState<any>(null),[error,setError]=useState(''),[selected,setSelected]=useState<any>(null),[scenario,setScenario]=useState('target'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<any>(null);const request=useRef('');
 async function refresh(){setData(await api('/api/trading'));await refreshProduct()}
 // F8: poll /api/trading every 5s only while this screen is on screen (its dock/sheet panel is visible and the browser tab isn't hidden); resuming pulls immediately.
 const panelVisible=usePanelVisible(),[pageVisible,setPageVisible]=useState(()=>(globalThis as any).document?.visibilityState!=='hidden'),polling=panelVisible&&pageVisible;
 useEffect(()=>{const doc=(globalThis as any).document;if(Platform.OS!=='web'||!doc?.addEventListener)return;const on=()=>setPageVisible(doc.visibilityState!=='hidden');doc.addEventListener('visibilitychange',on);return()=>doc.removeEventListener('visibilitychange',on)},[]);
 useEffect(()=>{if(!polling)return;let active=true;const pull=()=>api('/api/trading').then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(e.message)});pull();const timer=setInterval(pull,5000);return()=>{active=false;clearInterval(timer)}},[polling]);
 async function act(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await refresh();setConfirm(null)}catch(e:any){setError(planError(e));if(e?.code==='DATA_STALE')setRefusedStale(true)}finally{setBusy(false)}}
 function review(p:any){request.current=Crypto.randomUUID();setSelected(p);setConsent(false);setScenario('target');setError('')}
 const plans=(product.plans||[]).filter((p:any)=>p.status==='draft'||p.status==='illustrative'),wallet=data?.wallet;const active=(data?.orders||[]).filter((o:any)=>['queued','partial','open'].includes(o.status));
 return <DeskPage><Head title="A plan. A controlled next step." detail="Review your setup, test the order journey and follow every outcome."/><Message error={error}/><View style={[s.card,{borderColor:'#285546'}]}><View style={[s.between,{flexWrap:'wrap'}]}><Badge label="VIRTUAL WORKFLOW ACCOUNT" tone="amber"/><Badge label="LIVE ORDERS DISABLED" tone="neutral"/></View><T style={{fontSize:15,lineHeight:25,color:C.muted}}>These are artificial price scenarios for testing entry, risk and exit handling. The virtual results are separate from your stock’s historical backtest. Capital figures exclude scenario outcomes.</T><View style={{flexDirection:layoutMode(width)!=='phone'?'row':'column',gap:22}}>{[['Starting capital',wallet?.initial_paise],['Available virtual cash',wallet?wallet.available_capital_paise??wallet.initial_paise-wallet.reserved_paise:undefined],['Reserved for open simulations',wallet?.reserved_paise]].map(([l,v])=><View key={String(l)} style={{flex:1,gap:7}}><T style={{fontSize:13,color:C.muted}}>{l}</T><T style={{fontSize:26,fontFamily:'ManropeBold'}}>{v==null?'—':money(Number(v)/100)}</T></View>)}</View>{wallet?.loss_limit_paise!=null&&<T style={{fontSize:13,lineHeight:20,color:wallet.loss_limit_reached?C.red:C.muted}}>{wallet.loss_limit_reached?'Loss limit reached - new simulated entries are blocked. ':''}Realized scenario losses {money(Number(wallet.realized_loss_paise||0)/100)} of {money(Number(wallet.loss_limit_paise)/100)} limit. Scenario gains do not offset this limit.</T>}
 <View style={{gap:6,borderTopWidth:1,borderColor:C.line,paddingTop:14}}><View style={[s.between,{flexWrap:'wrap'}]}><T style={{fontSize:13,color:C.muted}}>Chosen-scenario outcome (synthetic)</T><Badge label="NOT CAPITAL · NOT MARKET RESULT" tone="amber"/></View><T style={{fontSize:20,fontFamily:'ManropeBold',color:C.muted}}>{wallet?money((wallet.scenario_outcome_total_paise??wallet.realized_paise)/100):'—'}</T><T style={{fontSize:13,lineHeight:21,color:C.muted}}>{wallet?`${wallet.scenario_outcome_count??0} closed simulation${wallet.scenario_outcome_count===1?'':'s'}. `:''}You picked each price scenario in Review test order. Outcomes are after assumed costs, are not market, historical or broker results, and are not added to your capital.</T></View>
 <View style={[s.row,{flexWrap:'wrap'}]}><Button label={wallet?.paused?'Resume new entries':'Pause new entries'} kind="outline" disabled={!wallet} loading={busy} onPress={()=>wallet?.paused?act(()=>api('/api/trading/pause',{paused:false})):setConfirm({kind:'pause'})}/><T style={{fontSize:13,color:C.muted}}>Open simulations can still exit while paused.</T></View></View>
 {stale&&<View accessibilityLiveRegion="polite" style={[s.card,{backgroundColor:C.amberBg}]}><T style={{fontSize:16,fontFamily:'InterSemi',color:C.amber}}>Fresh prices are needed before new simulations</T><T style={{fontSize:14,lineHeight:23,color:C.muted}}>Stored market data ends {dateText(state?.source_latest)} · {dataAgeText(age)}. New simulations are refused while stored prices are older than the allowed age. Your plans stay saved and research remains available; simulations can start again once prices are refreshed.</T></View>}
 <T style={{fontSize:22,fontFamily:'ManropeBold'}}>Ready for your review <T style={{color:C.muted}}>({plans.length})</T></T>
 {loading&&!plans.length?<Loading/>:plans.length?plans.map((p:any)=>{
  const illustrative=p.status==='illustrative'||p.illustrative===true,legacy=p.evidence_check==='legacy',ready=simulatable(p);
  return <View key={p.id} style={s.card}>
   <View style={[s.between,{flexWrap:'wrap'}]}><View style={{gap:5}}><T style={{fontFamily:'InterSemi',fontSize:19}}>{p.symbol}</T><T style={{fontSize:14,color:C.muted}}>{p.pattern_name} · {p.timeframe} · {p.side}</T></View><Badge label={illustrative?'ILLUSTRATIVE':'DRAFT'} tone={illustrative?'amber':'neutral'}/></View>
   {illustrative&&<T style={{fontSize:13,lineHeight:21,fontFamily:'InterMedium',color:C.amber}}>Illustrative · no tested evidence for this exit rule · can’t be simulated</T>}
   {legacy&&<T style={{fontSize:13,lineHeight:21,color:C.amber}}>Saved before evidence checks. {p.tradable_evidence===true?'Its rule was the frozen tested rule.':'Its exits have no exact-rule evidence; prepare it again before relying on it.'}</T>}
   {!legacy&&p.tradable_evidence!==true&&!!p.tradable_reason&&<T style={{fontSize:12,lineHeight:19,color:C.muted}}>{p.tradable_reason}</T>}
   <Row label="Planned capital" value={money(p.notional)}/>
   <Row label="Stop / reward to risk" value={`${p.stop_pct?.toFixed(2)}% / ${p.reward?.toFixed(2)}:1`}/>
   <Row label="Planned maximum hold" value={p.exit_evidence?.holding?.label||`${p.hold} completed ${p.timeframe} candles`}/>
   <View style={[s.row,{flexWrap:'wrap'}]}>
    {ready&&<Button label="Review test order" disabled={wallet?.paused} onPress={()=>review(p)}/>}
    {p.research_context&&<Button label="Source historical study" kind="outline" onPress={()=>{setStudyDraft({...p.research_context.settings,jobId:p.research_context.id});router.push('/simulate' as any)}}/>}
    <Button label={illustrative?'Archive plan':'Archive draft'} kind="ghost" onPress={()=>setConfirm({kind:'archive',id:p.id,symbol:p.symbol})}/>
   </View>
   {!ready&&!illustrative&&<T style={{fontSize:12,color:C.muted}}>Test orders need tested evidence for this exact exit rule. Prepare the plan again from Discover.</T>}
  </View>}):<Empty title="Start with a chart you understand" detail="Open a setup, review its evidence and save a plan. It will arrive here for your next step." action={<Button label="Discover setups" onPress={()=>router.push('/chart')}/>}/>}
 <View style={s.between}><T style={{fontSize:22,fontFamily:'ManropeBold'}}>Orders & outcomes</T><T style={{fontSize:13,color:C.muted}}>{data?`${active.length} active`:''}</T></View>
 {!data?<T style={{fontSize:15,color:C.muted}}>{error?'Orders could not be loaded yet. This page retries every few seconds.':'Loading your simulated orders…'}</T>:!data.orders?.length&&<T style={{fontSize:15,color:C.muted}}>Your first simulated order will appear here.</T>}
 {(data?.orders||[]).map((o:any)=><View key={o.id} style={s.card}>
  <View style={[s.between,{flexWrap:'wrap'}]}><T style={{fontSize:18,fontFamily:'InterSemi'}}>{o.symbol} <T style={{fontSize:13,color:C.muted}}>{o.product} · {o.mode}</T></T><Badge label={o.status.toUpperCase()} tone={o.status==='rejected'?'red':o.status==='closed'?'green':'amber'}/></View>
  <Row label="Filled quantity" value={`${o.filled_qty} / ${o.payload.plan?.quantity||o.payload.quantity||'—'}`}/>
  <Row label="Average fill" value={o.average_paise?money(o.average_paise/100):'Awaiting fill'}/>
  {o.mode==='simulation'&&<><Row label="Scenario you chose" value={o.payload.scenario}/><Row label={`Outcome of the scenario you chose (${o.payload.scenario}) — synthetic, after assumed costs`} value={['queued','partial','open'].includes(o.status)?'Recorded at close':money(o.realized_paise/100)}/><Row label="Favorable / adverse move" value={`${Number(o.payload.mfe_pct||0).toFixed(2)}% / ${Number(o.payload.mae_pct||0).toFixed(2)}%`}/></>}
  {o.payload.reason&&<T style={{fontSize:14,color:C.muted}}>{o.payload.reason}</T>}
  <T style={{fontSize:12,color:C.muted}}>{stamp(o.updated)}</T>
  <View style={[s.row,{flexWrap:'wrap'}]}>{o.mode==='simulation'&&['queued','partial','open'].includes(o.status)&&<Button label="Advance scenario" kind="outline" loading={busy} onPress={()=>act(()=>api('/api/trading/advance',{id:o.id}))}/>} {o.status==='queued'&&<Button label="Cancel unfilled order" kind="ghost" onPress={()=>setConfirm({kind:'cancel',id:o.id,symbol:o.symbol})}/>} {['partial','open'].includes(o.status)&&<Button label="Exit simulation" kind="ghost" onPress={()=>setConfirm({kind:'exit',id:o.id,symbol:o.symbol})}/>}</View>
 </View>)}
 <View style={s.card}><T style={{fontSize:19,fontFamily:'InterSemi'}}>Your live trading connection</T><T style={{fontSize:15,lineHeight:25,color:C.muted}}>Kite authorization and live execution are separate. Live execution stays locked for this release while broker approval, fresh data, operating limits and the execution review are completed.</T><Button label="Manage Kite connection" kind="outline" onPress={()=>router.push('/account')}/></View>
 <Sheet visible={!!selected} onClose={()=>setSelected(null)} title={`Review ${selected?.symbol||''}`} subtitle="Synthetic workflow simulation">
  <Message error={error}/>
  <T style={{fontSize:15,lineHeight:25,color:C.muted}}>The saved chart price sets the scale only. Artificial price steps run in seconds to test order handling; they do not reproduce the chart’s holding period or predict the market.</T>
  <Row label="Quantity" value={selected?.quantity}/><Row label="Virtual capital reserved" value={money((selected?.notional||0)+(selected?.reserved_cost||0))}/><Row label="Planned risk including assumed costs" value={money(selected?.planned_risk)}/>
  <T style={{fontSize:15,fontFamily:'InterSemi'}}>Choose the behavior to test</T>
  <View style={{gap:10}}>{[['target','Move toward target'],['stop','Stop reached'],['gap','Gap beyond stop'],['partial','Partial fill, then continuation'],['rejected','Broker rejection']].map(([v,l])=><Chip key={v} label={l} active={scenario===v} onPress={()=>{setScenario(v);request.current=Crypto.randomUUID()}}/>)}</View><Consent value={consent} onChange={setConsent}>I understand this uses synthetic prices and virtual money. No broker order will be sent.</Consent>{!!selected&&!simulatable(selected)&&<T accessibilityRole="alert" style={{fontSize:13,color:C.amber}}>This plan has no tested evidence for its exact exit rule, so it can’t be simulated.</T>}{stale&&<T accessibilityRole="alert" style={{fontSize:13,lineHeight:21,color:C.amber}}>{dataAgeText(age)} (stored data ends {dateText(state?.source_latest)}). Fresh prices are needed, so the server will refuse this simulation if the data is older than its allowed age.</T>}<Button label="Start this simulation" loading={busy} disabled={!consent||!simulatable(selected)} onPress={()=>act(async()=>{await api('/api/trading/simulate',{plan_id:selected.id,request_id:request.current,scenario,acknowledge_synthetic:true});setSelected(null)})}/></Sheet>
 <Sheet visible={!!confirm} onClose={()=>setConfirm(null)} title={confirm?.kind==='pause'?'Pause new simulated entries?':`${confirm?.kind==='archive'?'Archive plan':confirm?.kind==='exit'?'Exit simulation':'Cancel order'} · ${confirm?.symbol||''}`}><T style={{fontSize:16,lineHeight:26}}>{confirm?.kind==='pause'?'No new simulations can start until you resume. Filled simulations can still advance to their exits or be exited by you. Queued orders wait unfilled and can still be cancelled.':confirm?.kind==='archive'?'The draft will leave your review list. Existing orders are managed separately.':confirm?.kind==='exit'?'Close the filled virtual quantity at the current synthetic mark and release its reserved capital.':'Cancel the unfilled simulated order and release its reserved capital.'}</T><Button label={confirm?.kind==='pause'?'Pause new entries':'Confirm'} loading={busy} onPress={()=>act(()=>confirm.kind==='pause'?api('/api/trading/pause',{paused:true}):api(confirm.kind==='archive'?'/api/product/plan-action':'/api/trading/'+confirm.kind,confirm.kind==='archive'?{id:confirm.id,action:'archive'}:{id:confirm.id}))}/></Sheet>
 </DeskPage>
}
export function Recovery(){const params=useLocalSearchParams(),[password,setPassword]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);return <FormPage title={done?'Your password is updated.':'Recover your account.'} detail={done?'All prior sessions have been revoked. Sign in with your new password.':'Use the private recovery link supplied by the pilot owner.'}><Message error={error}/>{done?<Button label="Sign in" onPress={()=>router.replace('/signin')}/>:<><Field label="New password · at least 12 characters" value={password} onChangeText={setPassword} secure autoComplete="new-password"/><Button label="Set my new password" disabled={password.length<12||!params.code} loading={busy} onPress={async()=>{setBusy(true);try{await api('/api/auth/recover',{code:String(params.code),password});setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}/></>}</FormPage>}
