import React,{useEffect,useMemo,useState} from 'react';
import {View,Pressable,ScrollView,TextInput,useWindowDimensions} from 'react-native';
import {router} from 'expo-router';
import Svg,{Path} from 'react-native-svg';
import {useProduct} from './context';
import {C,T,s,Button,Chip,Badge,Empty,Loading,BREAKPOINTS,layoutMode,useLayoutMode} from './ui';
import {Match,api,filterMatches,pct,dateText} from './model';
import {decision,Verdict,discoverDefaults} from './decision';
import {TIMEFRAMES} from './constants';
import {AgentCase} from './AgentCase';
import {WatchRow,useWatchRemoval} from './widgets/WatchWidget';
import {AgentMark} from './TraderShell';
const sparkCache=new Map<string,number[]>();
function Spark({match}:any){const cacheKey=match.id+':'+match.candle_end;const [values,setValues]=useState<number[]>(sparkCache.get(cacheKey)||[]);useEffect(()=>{let active=true;if(sparkCache.has(cacheKey)){setValues(sparkCache.get(cacheKey)!);return}api(`/api/chart?symbol=${encodeURIComponent(match.symbol)}&timeframe=${match.timeframe}`).then(d=>{const points=d.bars.slice(-28).map((b:any)=>b.close);sparkCache.set(cacheKey,points);if(active)setValues(points)}).catch(()=>{});return()=>{active=false}},[cacheKey]);if(values.length<2)return <View style={{width:64,height:24}}/>;const lo=Math.min(...values),span=Math.max(...values)-lo||1;const path=values.map((v,i)=>`${i?'L':'M'}${i/(values.length-1)*62+1},${23-(v-lo)/span*21}`).join(' ');return <Svg width={64} height={26} viewBox="0 0 64 26" accessibilityLabel="Last 28 stored closes"><Path d={path} fill="none" stroke={values[values.length-1]>=values[0]?C.green:C.red} strokeWidth={1.3}/></Svg>;}
function StockRow({match,selected,onPress}:any){const {filters}=useProduct();const d=decision(match,filters);return <Pressable accessibilityRole="button" accessibilityLabel={`Inspect ${match.symbol} ${match.timeframe} ${match.pattern_name}`} onPress={onPress} style={({pressed})=>[{flexDirection:'row',gap:11,padding:14,paddingVertical:16,borderBottomWidth:1,borderColor:C.line,backgroundColor:selected?'#0D2427':pressed?C.paper:'transparent',borderLeftWidth:2,borderLeftColor:selected?C.green:'transparent'}]}><View style={{width:36,height:36,borderRadius:18,borderWidth:1,borderColor:'#47616E',backgroundColor:'#D8E7ED',alignItems:'center',justifyContent:'center'}}><T style={{fontFamily:'ManropeBold',fontSize:11,color:'#10212C'}}>{match.symbol.slice(0,2)}</T></View><View style={{flex:1,gap:4}}><View style={s.between}><T style={{fontFamily:'InterSemi',fontSize:13}}>{match.symbol}</T><Badge label={d.title.toUpperCase()} tone={d.verdict==='review'?'green':d.verdict==='watch'?'amber':'neutral'}/></View><T style={{fontSize:11,color:C.muted}}>{match.pattern_name} · {match.timeframe}</T><View style={s.between}><View style={{gap:2}}><T style={{fontSize:12,color:(d.stats?.expectancy_pct||0)>0?C.green:C.red}}>{pct(d.stats?.display_return_pct)}<T style={{fontSize:10,color:C.muted}}> past avg.</T></T><T style={{fontSize:10,color:C.muted}}>{d.stats?.n||0} trades · {d.stats?.holding?.duration||'No holding study'}</T></View><Spark match={match}/></View></View></Pressable>;}
// DeskEmbedded (Phase 0 shell): true when the page is mounted inside a workspace dock tab, which drops the full-page 30px padding. Content is unchanged.
export const DeskEmbedded=React.createContext(false);
export function DeskPage({children}:any){const phone=useLayoutMode()==='phone',embedded=React.useContext(DeskEmbedded);return <View style={{width:'100%',maxWidth:1440,alignSelf:'center',paddingHorizontal:phone||embedded?16:30,paddingVertical:phone||embedded?16:30,gap:phone?16:22,paddingBottom:35}}>{children}</View>;}
export function TraderDesk(){
 const {state,matches,filters,setFilters,query,setQuery,setFilterOpen,setDetail,loading,error,refresh,setStock,product,defaultFilters}=useProduct();const {width:screen}=useWindowDimensions();const split=screen>=BREAKPOINTS.desktop;
 const phone=layoutMode(screen)==='phone';
 // Resets and guided commands start from the same safe defaults as Discover (minimum trades = MIN_TRADES_DEFAULT, onboarding timeframes).
 const safe=defaultFilters||discoverDefaults();
 const [verdict,setVerdict]=useState<Verdict|'all'>('review'),[selected,setSelected]=useState(''),[limit,setLimit]=useState(6),[intent,setIntent]=useState(''),[notice,setNotice]=useState(''),[method,setMethod]=useState(false),[stockHits,setStockHits]=useState<any[]>([]),[commandOpen,setCommandOpen]=useState(false),[caseRevision,setCaseRevision]=useState(0);
 const filtered=useMemo(()=>filterMatches(matches,filters,query),[matches,filters,query]);const counts={review:0,watch:0,pass:0};filtered.forEach(m=>counts[decision(m,filters).verdict]++);
 const rows=filtered.filter(m=>verdict==='all'||decision(m,filters).verdict===verdict);const current=rows.find(m=>m.id===selected)||rows[0];
 useEffect(()=>setLimit(6),[filters,query,verdict]);
 useEffect(()=>{let active=true;setStockHits([]);if(query.length<2)return;const timer=setTimeout(()=>api('/api/stocks?q='+encodeURIComponent(query)).then(d=>{if(active)setStockHits(d.slice(0,4))}).catch(()=>{}),250);return()=>{active=false;clearTimeout(timer)}},[query]);
 function command(text:string){const q=text.toLowerCase().trim();if(!q)return;let f={...safe};const tf=q.match(/\b(1h|4h|1d|1w)\b/);if(tf)f.timeframe=tf[1].toUpperCase();if(q.includes('bull'))f.direction='bullish';if(q.includes('bear'))f.direction='bearish';if(/2\s*[-–]\s*5/.test(q))f.band='2_5';if(/1\s*[-–]\s*2/.test(q))f.band='1_2';if(/5\s*[-–]\s*10/.test(q))f.band='5_10';if(/over 10|>\s*10/.test(q))f.band='over_10';const stock=matches.find((m:Match)=>m.symbol.toLowerCase()===q);const pattern=state?.patterns?.find((p:any)=>q.includes(p.name.toLowerCase()));if(stock||pattern){setQuery(stock?.symbol||pattern.name);setFilters(f);setVerdict('all');}else if(tf||f.band||f.direction!=='all'){setFilters(f);setQuery('');setVerdict('review');}else{setQuery(text.trim());setVerdict('all');}setNotice(`Your focus: ${text}. Each result still uses that stock’s own history.`);setIntent('');}
 if(loading)return <Loading/>;if(error&&!state)return <DeskPage><Empty title="Let’s reconnect your agent" detail={error} action={<Button label="Reconnect" onPress={refresh}/>}/></DeskPage>;
 return <DeskPage>
  <View style={[s.between,{alignItems:'flex-start'}]}><View style={{gap:6}}><View style={s.row}><T style={{fontFamily:'ManropeBold',fontSize:phone?25:32,lineHeight:40,letterSpacing:-.8}}>Trader Agent</T><View style={{width:6,height:6,borderRadius:3,backgroundColor:C.green}}/></View>{!phone&&<T style={{fontSize:12,color:C.muted}}>The market, reviewed. Your next move, explained.</T>}</View><View style={{alignItems:'flex-end',gap:6}}><Badge label={state?.source_stale?'HISTORICAL REPLAY':'COMPLETED CANDLES'} tone="amber"/><T style={{fontSize:10,color:C.muted}}>{dateText(state?.source_latest)}</T></View></View>
  {phone?<View style={{borderWidth:1,borderColor:'#20413E',backgroundColor:'#0B1E22',borderRadius:11,padding:13,gap:13}}><View style={s.row}><AgentMark size={23}/><T style={{fontFamily:'InterMedium',fontSize:12,flex:1}}>{counts.review} setups for review. {state?.source_stale?'Fresh prices come next.':'Open one to see the reasoning.'}</T></View><View style={[s.row,{justifyContent:'space-around'}]}>{[[state?.universe,'stocks covered'],[matches.length,'patterns stored'],[filtered.length,'with your history filter']].map(([v,l],i)=><View key={i} style={{flex:1,gap:3,alignItems:'center'}}><T style={{fontFamily:'ManropeBold',fontSize:20,color:C.green}}>{Number(v||0).toLocaleString()}</T><T style={{fontSize:8,color:C.muted,textAlign:'center'}}>{l}</T></View>)}</View></View>:<>
  <View style={{flexDirection:split?'row':'column',gap:18}}>
   <View style={{flex:1,backgroundColor:'#0B1E22',borderWidth:1,borderColor:'#20413E',borderRadius:13,padding:18,gap:12}}>
    <View style={[s.row,{alignItems:'flex-start',gap:12}]}><AgentMark size={28}/><View style={{flex:1,gap:6}}><T style={{fontSize:split?17:15,lineHeight:24,fontFamily:'InterMedium'}}>{counts.review?`${counts.review} setups are worth a closer look.`:'Nothing clears your current review screen.'}</T><T style={{fontSize:12,color:C.muted,lineHeight:20}}>I’ve separated positive past averages from uncertain or weak histories. {state?.source_stale?'Fresh candles are needed before any trade can move forward.':'Open a setup to inspect its structure and next conditions.'}</T></View></View>
    <Pressable accessibilityRole="button" accessibilityLabel="How the agent decided" onPress={()=>setMethod(!method)} style={{minHeight:35,justifyContent:'center',paddingLeft:40}}><T style={{fontSize:11,color:C.green}}>{method?'Hide decision rules':'See how I made the cut'}  {method?'−':'+'}</T></Pressable>
    {method&&<T style={{fontSize:12,color:C.muted,lineHeight:22}}>For review: a directional pattern and positive past average with at least {filters.minimum} historical trades. Watch: unresolved direction or insufficient evidence. Pass: a non-positive average after assumed costs. These are transparent screening rules, not a probability forecast.</T>}
   </View>
   <View style={{flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:C.line,borderRadius:13,padding:18,gap:20,justifyContent:'space-around',minWidth:split?330:undefined}}>{[[state?.universe,'stocks covered'],[matches.length,'patterns stored'],[filtered.length,`${filters.minimum}+ trade history`]].map(([v,l],i)=><View key={i} style={{alignItems:'center',gap:6,flex:1}}><T style={{fontFamily:'ManropeBold',fontSize:23,color:i===1?C.green:C.ink}}>{Number(v||0).toLocaleString()}</T><T style={{fontSize:9,color:C.muted,textAlign:'center'}}>{l}</T></View>)}</View>
  </View>
  </>}
  {(!phone||commandOpen)&&<View style={{gap:10}}><View style={[s.row,{borderWidth:1,borderColor:C.line,backgroundColor:C.paper,borderRadius:12,paddingLeft:14,paddingRight:5}]}><AgentMark size={23}/><TextInput accessibilityLabel="Tell your agent what to find" value={intent} onChangeText={setIntent} onSubmitEditing={()=>command(intent)} placeholder="Try “bullish 4H”, a stock or a pattern…" placeholderTextColor={C.muted} returnKeyType="search" style={{flex:1,fontFamily:'Inter',fontSize:12,color:C.ink,minHeight:50}}/><Button label="Find" icon="arrow-right" kind="ghost" onPress={()=>command(intent)}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{['Bullish 4H','2–5% past return','Cup & Handle'].map(t=><Chip key={t} label={t} onPress={()=>command(t)}/>)}<Chip label="Reset focus" icon="rotate-ccw" onPress={()=>{setFilters(safe);setQuery('');setNotice('');setVerdict('review')}}/></ScrollView>{!!notice&&<T style={{fontSize:11,color:C.green}}>{notice}</T>}</View>}
  <View style={{flexDirection:split?'row':'column',gap:24,alignItems:'flex-start'}}><View style={{width:split?440:'100%',gap:14}}>
   <View style={s.between}><T style={{fontFamily:'InterSemi',fontSize:15}}>{phone?'Setups':'Your decision feed'}</T><View style={s.row}>{phone&&<Button label="Ask / search" icon="search" kind="ghost" onPress={()=>setCommandOpen(!commandOpen)}/>}<Button label="Filters" icon="sliders" kind="outline" onPress={()=>setFilterOpen(true)} style={{minHeight:39,paddingVertical:8}}/></View></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:6}}>{[['review',`For review ${counts.review}`],['watch',`Watch ${counts.watch}`],['pass',`Pass ${counts.pass}`],['all',`All ${filtered.length}`]].map(([v,l])=><Chip key={v} label={l} active={verdict===v} onPress={()=>setVerdict(v as any)}/>)}</ScrollView>
   {<View style={s.between}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:15}}>{['All',...TIMEFRAMES].map(tf=><Pressable key={tf} accessibilityRole="button" accessibilityLabel={tf==='All'?'All timeframes':tf} accessibilityState={{selected:filters.timeframe===tf}} aria-selected={filters.timeframe===tf} onPress={()=>setFilters({...filters,timeframe:tf})} style={{minHeight:44,paddingHorizontal:9,justifyContent:'center',borderBottomWidth:2,borderBottomColor:filters.timeframe===tf?C.green:'transparent'}}><T style={{fontSize:11,color:filters.timeframe===tf?C.green:C.muted}}>{tf==='All'?'All timeframes':tf}</T></Pressable>)}</ScrollView></View>}
   {!!query&&<View style={s.between}><T style={{fontSize:12,color:C.muted,flex:1}}>Search: {query}</T><Button label="Clear search" kind="ghost" onPress={()=>setQuery('')}/></View>}
   {!!stockHits.length&&<View style={{gap:7}}><T style={s.label}>Stock overview</T>{stockHits.map(stock=><Button key={stock.symbol} label={`Open ${stock.symbol} stock overview`} kind="outline" onPress={()=>setStock(stock)}/>)}</View>}
   {rows.length?<View style={{borderWidth:1,borderColor:C.line,borderRadius:13,overflow:'hidden'}}>{rows.slice(0,limit).map(m=><StockRow key={m.id} match={m} selected={split&&m.id===current?.id} onPress={()=>{if(split){setSelected(m.id);setCaseRevision(v=>v+1)}else setDetail(m)}}/>)}</View>:<Empty title="No setups in this view" detail="Change your focus or let the agent show all available histories." action={<Button label="Show all decisions" kind="outline" onPress={()=>setVerdict('all')}/>}/>}
   {rows.length>limit&&<Button label={`Show more · ${rows.length-limit} remaining`} kind="outline" onPress={()=>setLimit(limit+12)}/>}
   <T style={{fontSize:10,color:C.muted}}>Ordered by pattern fit within each decision. Sparklines show stored closes, not future paths.</T>
  </View>{split&&<View style={{flex:1,minWidth:0,borderWidth:1,borderColor:C.line,borderRadius:14,padding:25,backgroundColor:'#08131A'}}>{current?<AgentCase key={current.id+':'+caseRevision} match={current}/>:<Empty title="Your next setup will appear here" detail="Select a stock from the agent’s feed to open its chart and reasoning."/>}</View>}</View>
 </DeskPage>;
}
export function WatchDesk(){
 const {product,setDetail,state}=useProduct();const watches=product.watchlist||[];
 // Cards, status wording and the remove confirmation are shared with the sidebar WatchWidget (src/widgets/WatchWidget.tsx).
 const [direction,setDirection]=useState('all'),removal=useWatchRemoval();
 const shown=watches.filter((w:any)=>direction==='all'||w.direction===direction);
 return <DeskPage>
  <View style={s.between}><View style={{gap:8}}><T style={{fontFamily:'ManropeBold',fontSize:30,lineHeight:38}}>My watch</T><T style={{fontSize:12,color:C.muted}}>One place for the setups you want followed through.</T></View><AgentMark size={38}/></View>
  <View style={[s.card,{backgroundColor:'#0B1E22',borderColor:'#20413E'}]}><T style={{fontFamily:'InterMedium'}}>I’ll keep the conditions in view.</T><T style={{fontSize:12,color:C.muted}}>Saved setups are compared with each refreshed scan while KANIDA is open. {state?.source_stale?'Fresh candles are still needed for a new market decision.':'Open a setup to review the latest completed candle.'}</T></View>
  <View style={s.row}>{[['all','All'],['bullish','Bullish basket'],['bearish','Bearish basket']].map(([v,l])=><Chip key={v} label={l} active={direction===v} onPress={()=>setDirection(v)}/>)}</View>
  {!shown.length?<Empty icon="eye" title="Give your agent something to watch" detail="Open a setup and choose Add to watch. Its pattern, timeframe and next conditions stay together here." action={<Button label="Discover setups" icon="arrow-right" onPress={()=>router.push('/chart')}/>}/>:shown.map((w:any)=><WatchRow key={w.id} item={w} variant="card" onReview={(m:Match)=>setDetail(m)} onRemove={()=>removal.setRemoving(w)}/>)}
  <T style={{fontSize:11,color:C.muted}}>Basket returns, win rate and drawdown need a shared-capital simulation. Stock-level histories remain separate.</T>
  {removal.sheet}
 </DeskPage>;
}
