"""AUTO-GENERATED by the agent. Do not hand-edit.

Rules the agent composed itself and kept because they
improved the forward-test fitness.
"""

CONFIG = {
    "min_n": 29,
    "top_patterns": 1,
    "min_edge1": 0.117,
    "min_strength1": -0.06,
    "require_consistency": 0,
    "combo_depth": 2,
    "side": "long",
    "rank_by": "strength1",
    "min_hist": 150,
    "max_conditions": 4,
    "recency_weight": 0.0,
    "horizon": 2
}

INVENTED_RULES = [
    ('INV_roc_60<_body_p<_n_high>_9_0', [["roc_60", "<=", 3.417905149572642], ["body_pct", "<=", 0.3749999999997032], ["n_higher_highs_5d", ">", 1.0]]),
    ('INV_range_>_dist_h<_9_1', [["range_pct", ">", 1.8820378557518909], ["dist_high_120", "<=", -18.003487923482847]]),
    ('INV_n_sub_>_weekly<_9_2', [["n_sub_75v_7d", ">", 1.0], ["weekly_breakout_20w", "<=", 0.0]]),
    ('INV_dist_s>_n_high>_9_3', [["dist_sma_50", ">", 0.6186565731150062], ["n_higher_lows_5d", ">", 2.0]]),
    ('INV_rs_mar>_upper_>_n_high>_9_4', [["rs_market_20d", ">", -5.177788283802309], ["upper_wick_pct", ">", 0.45714285714282615], ["n_higher_highs_5d", ">", 3.0]]),
    ('INV_upper_>_rs_mar>_9_5', [["upper_wick_pct", ">", 0.3023255813953087], ["rs_market_20d", ">", -5.177788283802309]]),
    ('INV_dist_h<_dist_h<_dist_h<_weekly<_9_6', [["dist_high_252", "<=", -21.876800877204715], ["dist_high_120", "<=", -4.0282894317330875], ["dist_high_60", "<=", -3.1841301263179096], ["weekly_close_vs_sma20", "<=", -3.7305710313685903]]),
    ('INV_rs_mar<_n_high>_weekly<_vol_5d>_9_7', [["rs_market_20d", "<=", 1.9858047952191038], ["n_higher_lows_5d", ">", 2.0], ["weekly_close_vs_sma20", "<=", 6.973842293703036], ["vol_5d_vs_20d", ">", 1.1017525803658972]]),
    ('INV_weekly>_slope_>_9_8', [["weekly_close_loc", ">", 0.8073730468448821], ["slope_sma_20", ">", -0.4131979988139744]]),
    ('INV_gap_pc<_atr_20<_dist_h<_9_9', [["gap_pct", "<=", 0.19701701511437575], ["atr_20_pct", "<=", 2.358103691252376], ["dist_high_252", "<=", -6.703672296924196]]),
    ('INV_close_>_slope_>_atr_20<_9_10', [["close_loc", ">", 0.7857142857142229], ["slope_sma_20", ">", 0.1681032088236445], ["atr_20_pct", "<=", 2.798635059551014]]),
    ('INV_close_>_dist_s<_dist_h<_range_>_9_11', [["close_loc", ">", 0.3341742160278608], ["dist_sma_20", "<=", 0.3761958889140993], ["dist_high_120", "<=", -22.409189111335152], ["range_pct", ">", 1.8820378557518909]]),
]
