import React,{useState,useMemo,useEffect} from 'react';
import {View,TextInput,Pressable,ScrollView,useWindowDimensions,Linking,Platform} from 'react-native';
import {router} from 'expo-router';
import Svg,{Circle,Path,Line,Rect} from 'react-native-svg';
import qrcode from 'qrcode-generator';
import {useProduct} from './context';
import {C,T,s,Icon,Button,Chip,Badge,Stat,Empty,Loading} from './ui';
import {Match,History,filterMatches,histories,pct,money,dateText,bands,initialFilters,api} from './model';
import {CandleChart} from './Chart';
import {Rule} from './Sheets';

export function Page({children}:any){const {width}=useWindowDimensions();return <View style={{width:'100%',maxWidth:1390,alignSelf:'center',padding:width<700?20:width<1100?28:40,gap:width<700?18:26,paddingBottom:44}}>{children}</View>;}
function Heading({eyebrow,title,detail,action}:any){const {width}=useWindowDimensions();return <View style={[s.between,{alignItems:'flex-start'}]}><View style={{gap:9,flex:1}}>{width>=700&&<T style={s.label}>{eyebrow}</T>}<T accessibilityRole="header" style={[s.title,{fontSize:width<700?30:38,lineHeight:width<700?39:48}]}>{title}</T>{detail&&<T style={{color:C.muted,fontSize:13,maxWidth:620}}>{detail}</T>}</View>{action}</View>;}
export function Orb({size=110}:any){return <Svg width={size} height={size} viewBox="0 0 120 120"><Circle cx="60" cy="60" r="46" stroke="#80B096" strokeWidth=".6" opacity=".45" fill="none"/><Circle cx="60" cy="60" r="30" stroke="#ABD9AE" strokeWidth=".6" opacity=".6" fill="none"/><Path d="M18 80 Q60 0 102 70 M14 60 Q70 113 102 40 M40 14 Q113 67 42 106" stroke="#BADDAB" fill="none" strokeWidth="1"/><Circle cx="60" cy="60" r="7" fill="#D6EEA7"/><Circle cx="90" cy="38" r="3" fill="#D6EEA7"/><Circle cx="28" cy="79" r="3" fill="#87B791"/></Svg>;}
function Avatar({symbol}:any){return <View style={{height:43,width:43,borderRadius:13,backgroundColor:C.soft,alignItems:'center',justifyContent:'center'}}><T style={{fontFamily:'ManropeBold',fontSize:14,color:C.green}}>{symbol.slice(0,2)}</T></View>;}
export function SetupCard({match,featured=false}: {match:Match;featured?:boolean}){
 const {filters,setDetail,setPlan}=useProduct();const h=histories(match,filters)[0]||match.history[0];const st=h?.reference;const {width}=useWindowDimensions();
 return <View style={[s.card,{padding:featured&&width>700?26:20,flex:1}]}>
  <View style={s.between}><View style={[s.row,{flex:1}]}><Avatar symbol={match.symbol}/><View style={{flex:1}}><T style={{fontFamily:'ManropeBold',fontSize:featured?21:17}}>{match.symbol}</T><T numberOfLines={1} style={{fontSize:11,color:C.muted}}>{match.sector}</T></View></View><Badge label={match.timeframe} tone="neutral"/></View>
  <View style={{gap:7}}><T style={{fontFamily:'InterSemi',fontSize:14}}>{match.pattern_name}</T><View style={[s.row,{flexWrap:'wrap'}]}><Badge label={match.direction==='neutral'?'Awaiting direction':match.direction==='bullish'?'Bullish':'Bearish'} tone={match.direction==='bearish'?'red':'green'}/><T style={{fontSize:10,color:C.muted}}>{match.state==='confirmed'?'Break confirmed':'Pattern formed'} · {match.score} fit</T></View></View>
  <View style={s.line}/><View style={s.between}><View><T style={{fontSize:11,color:C.muted}}>Past average return / trade</T><T style={{fontFamily:'ManropeBold',fontSize:featured?33:29,lineHeight:42,color:(st?.expectancy_pct||0)>=0?C.green:C.red,letterSpacing:-1}}>{pct(st?.display_return_pct)}</T></View><View style={{alignItems:'flex-end',gap:4,maxWidth:'50%'}}><T style={{fontSize:12,fontFamily:'InterMedium',textAlign:'right'}}>{st?.holding?.duration||'No holding study'}</T><T style={{fontSize:10,color:C.muted,textAlign:'right'}}>{h?.side==='short'?'Short-side history':'Long-side history'}</T></View></View>
  <T style={{fontSize:11,color:C.muted}}>Based on {st?.n||0} historical trades · after assumed costs{match.history.length>1?' · both directions in evidence':''}</T>
  {featured&&<CandleChart match={match} compact/>}
  <View style={s.row}><Button label="See evidence" kind="outline" onPress={()=>setDetail(match)} style={{flex:1}}/><Button label="AutoTrade" kind="soft" icon="arrow-up-right" disabled={!h} onPress={()=>setPlan({match,side:h?.side})} style={{flex:1}}/></View>
 </View>;
}

function BriefCard(){const {state}=useProduct();return <View style={[s.card,{backgroundColor:C.dark,borderColor:C.dark,padding:25,overflow:'hidden'}]}><View style={s.between}><T style={[s.label,{color:'#A2C2B0'}]}>KANIDA / BRIEFING</T><Icon name="command" color="#CBE5B6"/></View><View style={{alignItems:'center',marginTop:-12,marginBottom:-12}}><Orb size={145}/></View><T style={{fontFamily:'ManropeBold',fontSize:25,lineHeight:33,color:'#F2F5E8',letterSpacing:-.7}}>The whole market.{"\n"}A clearer next move.</T><T style={{fontSize:12,color:'#B5CABC'}}>I’ve organised {state?.matches||0} stored setups across four timeframes. Fresh prices are needed before we can act on them.</T><View style={{height:1,backgroundColor:'#355447'}}/><View style={s.between}><T style={{fontSize:12,color:'#B5CABC'}}>Current qualified setups</T><T style={{fontFamily:'ManropeBold',color:'#D6EEA7',fontSize:24}}>{state?.current_matches??'—'}</T></View><Button label="Open my briefing" kind="soft" icon="arrow-right" onPress={()=>router.push('/agent')}/></View>;}

export function Discover(){
 const {state,matches,filters,setFilters,query,setQuery,setFilterOpen,loading,error,refresh,setStock}=useProduct();const {width}=useWindowDimensions();
 const [limit,setLimit]=useState(9),[sort,setSort]=useState('fit'),[stockHits,setStockHits]=useState<any[]>([]);
 useEffect(()=>{let active=true;setStockHits([]);if(query.trim().length<2)return;const timer=setTimeout(()=>api('/api/stocks?q='+encodeURIComponent(query.trim())).then(rows=>{if(active)setStockHits(rows.slice(0,5))}).catch(()=>{}),250);return()=>{active=false;clearTimeout(timer)}},[query]);
 const results=useMemo(()=>{const a=filterMatches(matches,filters,query);if(sort==='return')a.sort((x,y)=>(histories(y,filters)[0]?.reference?.expectancy_pct??-Infinity)-(histories(x,filters)[0]?.reference?.expectancy_pct??-Infinity));if(sort==='sample')a.sort((x,y)=>(histories(y,filters)[0]?.reference?.n||0)-(histories(x,filters)[0]?.reference?.n||0));return a},[matches,filters,query,sort]);
 useEffect(()=>setLimit(9),[filters,query,sort]);
 const featured=results[0];const columns=width>=1380?3:width>=1000?2:1;
 const activeCount=Number(!!filters.band)+Number(!!filters.sector)+Number(!!filters.universe)+Number(filters.minimum!==5)+Number(filters.direction!=='all');
 if(loading)return <Loading/>;
 if(error&&!state)return <Page><Empty title="Let’s reconnect" detail={error} action={<Button label="Try again" onPress={refresh}/>}/></Page>;
 return <Page>
  <Heading eyebrow="YOUR MARKET, IN FOCUS" title={width<700?"Your next move.":"Less searching.\nMore conviction."} detail={width<700?"Patterns. Evidence. A considered plan.":"Discover the pattern. Understand the history. Build your plan."}/>
  <View style={[s.row,{backgroundColor:C.amberBg,padding:13,borderRadius:12,alignItems:'flex-start'}]}><Icon name="clock" color={C.amber} size={17}/><T style={{fontSize:12,color:C.amber,flex:1}}>{state?.source_stale?`Historical prices · ${dateText(state?.source_latest)}. Waiting for fresh candles.`:`Latest source ${dateText(state?.source_latest)} · candle-close scanning enabled.`}</T></View>
  <View style={[s.row,{gap:12}]}><View style={[s.row,{flex:1,backgroundColor:C.paper,borderWidth:1,borderColor:C.line,borderRadius:13,paddingHorizontal:15}]}><Icon name="search" color={C.muted}/><TextInput accessibilityLabel="Search stocks or patterns" placeholder="Search a stock or pattern…" placeholderTextColor={C.muted} value={query} onChangeText={setQuery} style={{fontFamily:'Inter',fontSize:14,color:C.ink,flex:1,minHeight:50}}/>{!!query&&<Pressable accessibilityLabel="Clear search" onPress={()=>setQuery('')} style={{padding:12}}><Icon name="x" size={16}/></Pressable>}</View><Button label={'Filters'+(activeCount?` · ${activeCount}`:'')} kind="outline" icon="sliders" onPress={()=>setFilterOpen(true)}/></View>
  {stockHits.length>0&&<View style={[s.card,{padding:16,gap:8}]}><T style={s.label}>Stocks · open all four timeframes</T>{stockHits.map((stock:any)=><Pressable key={stock.symbol} accessibilityRole="button" accessibilityLabel={`Open ${stock.symbol} stock overview`} onPress={()=>setStock(stock)} style={[s.between,{minHeight:50,paddingVertical:6}]}><View style={{flex:1}}><T style={{fontFamily:'InterSemi',fontSize:13}}>{stock.symbol}</T><T style={{fontSize:11,color:C.muted}}>{stock.company}</T></View><Icon name="arrow-up-right" color={C.green}/></Pressable>)}</View>}
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{['All','1H','4H','1D','1W'].map(tf=><Chip key={tf} label={tf==='All'?'All timeframes':tf} active={filters.timeframe===tf} onPress={()=>setFilters({...filters,timeframe:tf})}/>)}<View style={{width:1,backgroundColor:C.line,marginHorizontal:5}}/><Chip label="Historical snapshots" active={!filters.current} onPress={()=>setFilters({...filters,current:false})}/><Chip label={`Current · ${state?.current_matches||0}`} active={filters.current} onPress={()=>setFilters({...filters,current:true})}/></ScrollView>
  <View style={s.between}><View style={{gap:4,flex:1}}><T style={{fontFamily:'ManropeBold',fontSize:19}}>{query?`Matches for “${query}”`:filters.direction==='bullish'?'Bullish setups':filters.direction==='bearish'?'Bearish setups':'Your opportunity list'}</T><T style={{fontSize:11,color:C.muted}}>{results.length} setups · {new Set(results.map(m=>m.symbol)).size} stocks · {filters.minimum}+ historical trades{filters.band?' · '+bands.find(b=>b[0]===filters.band)?.[1]+' past average':''}</T></View>{width>750&&<View style={s.row}>{[['fit','Pattern fit'],['return','Past return'],['sample','Trade count']].map(([v,l])=><Chip key={v} label={l} active={sort===v} onPress={()=>setSort(v)}/>)}</View>}</View>
  {width<=750&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{[['fit','Pattern fit'],['return','Past return'],['sample','Trade count']].map(([v,l])=><Chip key={v} label={l} active={sort===v} onPress={()=>setSort(v)}/>)}</ScrollView>}
  {!results.length?<Empty title={filters.current?'No current setups yet':'No setups match these filters'} detail={filters.current?'The available source is historical. Explore the snapshots and their evidence while the engine waits for fresh prices.':'Try another return range, a different timeframe, or a smaller minimum trade count.'} action={<Button label={filters.current?'Explore historical snapshots':'Reset filters'} onPress={()=>{setFilters(filters.current?{...filters,current:false}:initialFilters);if(!filters.current)setQuery('')}}/>}/>:<>
   <View style={{flexDirection:width>=1150?'row':'column',gap:22,alignItems:'stretch'}}><View style={{flex:width>=1150?2:1}}><SetupCard match={featured} featured={width>700}/></View>{width>=1150&&<View style={{flex:1,maxWidth:360,gap:18}}><BriefCard/><View style={[s.card,{padding:20,gap:12}]}><View style={s.row}><Icon name="layers" size={17}/><T style={{fontFamily:'InterSemi',fontSize:13}}>Every timeframe, independent</T></View><T style={{fontSize:12,color:C.muted}}>1H · 4H · Daily · Weekly</T><T style={{fontSize:11,color:C.muted}}>{state?.universe?.toLocaleString()} stocks × {state?.patterns?.length} patterns. Each detector runs when its candle is complete.</T></View></View>}</View>
   <View style={{flexDirection:'row',flexWrap:'wrap',gap:18}}>{results.slice(1,limit).map(m=><View key={m.id} style={{width:columns===3?'32.1%':columns===2?'48.8%':'100%',flexGrow:1,maxWidth:columns===1?'100%':undefined}}><SetupCard match={m}/></View>)}</View>
   {results.length>limit&&<Button label={`Show more · ${results.length-limit} remaining`} kind="outline" onPress={()=>setLimit(limit+12)}/>}
  </>}
  <T style={{fontSize:11,color:C.muted,textAlign:'center'}}>Every return belongs to one stock × pattern × timeframe × direction. Historical performance can include losing trades.</T>
 </Page>;
}

export function Portfolios(){
 const {matches,state,filters,setFilters,setQuery}=useProduct();const {width}=useWindowDimensions();
 const base=filterMatches(matches,{...initialFilters,minimum:filters.minimum});
 const groups=[{key:'bullish',title:'Bullish patterns',detail:'Setups positioned for an upward move.',icon:'trending-up',color:C.green},{key:'bearish',title:'Bearish patterns',detail:'Setups positioned for a downward move.',icon:'trending-down',color:C.red}];
 return <Page><Heading eyebrow="PATTERN PORTFOLIOS" title="A thesis. A focused basket." detail="Bring related setups together, then build conviction stock by stock."/><View style={{flexDirection:width>1100?'row':'column',gap:22}}>{groups.map(g=>{const rows=base.filter(m=>m.direction===g.key);const names=Array.from(new Set(rows.map(m=>m.pattern_name)));return <View key={g.key} style={[s.card,{flex:1,padding:28}]}><View style={s.between}><View style={{backgroundColor:C.soft,padding:15,borderRadius:16}}><Icon name={g.icon} size={27} color={g.color}/></View><Badge label="Research basket" tone="neutral"/></View><T style={{fontFamily:'ManropeBold',fontSize:28,lineHeight:36,letterSpacing:-.8}}>{g.title}</T><T style={{color:C.muted,fontSize:13}}>{g.detail}</T><View style={[s.row,{flexWrap:'wrap',gap:7}]}>{names.map(n=><Badge key={n} label={n} tone="neutral"/>)}</View><View style={s.line}/><View style={s.row}><Stat label="Stocks in snapshots" value={new Set(rows.map(m=>m.symbol)).size}/><Stat label="Current setups" value={rows.filter(m=>m.current).length}/></View><T style={{fontSize:11,color:C.muted}}>{rows.length} setups · at least {filters.minimum} trades per stock study</T><View style={{backgroundColor:C.bg,padding:16,borderRadius:14,gap:8}}><T style={{fontFamily:'InterSemi',fontSize:12}}>KANIDA decision · Review evidence</T><T style={{fontSize:12,color:C.muted}}>Portfolio win rate, net expected return and drawdown are not calculated yet. The basket needs a shared-capital simulation.</T></View><Button label="Explore the basket" icon="arrow-right" onPress={()=>{setFilters({...initialFilters,minimum:filters.minimum,direction:g.key});setQuery('');router.push('/')}}/></View>})}</View>
  <View style={[s.card,{padding:26}]}><T style={{fontFamily:'ManropeBold',fontSize:21}}>From a basket to an automated portfolio</T><View style={{flexDirection:width>1050?'row':'column',gap:22}}><View style={{flex:1}}><Rule n="1" title="Qualify each stock" text="Use that stock’s pattern evidence, holding period, costs and sample size."/></View><View style={{flex:1}}><Rule n="2" title="Test shared capital" text="Account for overlapping trades, position sizes and sector concentration. Calculate drawdown along the equity path."/></View><View style={{flex:1}}><Rule n="3" title="Activate deliberately" text="Verify live data and execution rules, then review account limits before turning on automation."/></View></View></View>
  <View style={[s.row,{padding:8,alignItems:'flex-start'}]}><Icon name="git-branch" color={C.muted}/><T style={{fontSize:12,color:C.muted,flex:1}}>{base.filter(m=>m.direction==='neutral').length} setups are awaiting a directional breakout. You can find these under “Awaiting direction” in Discover.</T></View>
 </Page>;
}

export function AutoTrade(){
 const {product,refreshProduct,setToast,matches,setDetail}=useProduct();const {width}=useWindowDimensions();const [busy,setBusy]=useState(''),[error,setError]=useState(''),[archived,setArchived]=useState(false);
 const plans=product.plans.filter((p:any)=>archived?p.status==='archived':p.status!=='archived');
 async function action(id:string,action:string){setBusy(id);setError('');try{await api('/api/product/plan-action',{id,action});await refreshProduct();setToast(action==='resume'?'Plan returned to draft. No execution enabled.':'Paper plan updated.');}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <Page><Heading eyebrow="AUTOTRADE" title={"Your rules.\nYour control."} detail="A considered plan for every trade. Start in paper mode, with every decision visible." action={<Badge label="Paper planning" dot/>}/>
  <View style={[s.card,{backgroundColor:C.dark,borderColor:C.dark,padding:28}]}><View style={s.between}><View style={{gap:12,flex:1}}><T style={[s.label,{color:'#B4CCBA'}]}>EXECUTION STATUS</T><T style={{fontFamily:'ManropeBold',fontSize:27,lineHeight:35,color:'white'}}>Plan first. Activate when ready.</T><T style={{fontSize:13,color:'#B4CCBA',maxWidth:650}}>Build and save trade instructions here. A broker and forward paper execution engine are not connected, so no orders or live P&L are generated.</T></View>{width>750&&<Orb size={115}/>}</View></View>
  <View style={[s.card,{flexDirection:'row',flexWrap:'wrap'}]}><Stat label="Saved drafts" value={product.plans.filter((p:any)=>p.status==='draft').length}/><Stat label="Paused plans" value={product.plans.filter((p:any)=>p.status==='paused').length}/><Stat label="Open positions" value="0" note="Execution not connected"/><Stat label="Capital committed" value="₹0" note="Plans reserve no cash"/></View>
  <View style={s.between}><T style={{fontFamily:'ManropeBold',fontSize:21}}>{archived?'Archived plans':'Your trade plans'}</T><Button label={archived?'Show active drafts':'View archive'} kind="outline" onPress={()=>setArchived(!archived)}/></View>
  {error&&<T style={{color:C.red}}>{error}</T>}
  {!plans.length?<Empty icon="command" title={archived?'No archived plans':'Your first trade starts with a plan'} detail="Find a setup, inspect its stock-specific history, then tap AutoTrade to set capital, risk and exits." action={<Button label="Discover a setup" icon="arrow-right" onPress={()=>router.push('/')}/>}/>:plans.map((p:any)=><View key={p.id} style={s.card}><View style={s.between}><View style={[s.row,{flex:1}]}><Avatar symbol={p.symbol}/><View style={{flex:1}}><T style={{fontFamily:'ManropeBold',fontSize:20}}>{p.symbol}</T><T style={{fontSize:12,color:C.muted}}>{p.pattern_name} · {p.timeframe} · {p.side}</T></View></View><Badge label={p.status==='draft'?'Draft · not executing':p.status} tone={p.status==='paused'?'amber':'neutral'}/></View><View style={[s.row,{flexWrap:'wrap'}]}><Stat label="Planned allocation" value={money(p.notional)} note={`${p.quantity} whole shares at snapshot price`}/><Stat label="Stop distance" value={`${p.stop_pct}%`} note={`${p.reward}× target / stop`}/><Stat label="Planned risk + costs" value={money(p.planned_risk)} note="Gaps can exceed the stop"/></View><View style={s.line}/><T style={{fontSize:12,color:C.muted}}>Entry: next open after a new qualifying candle. Exit: stop, target or {p.hold} candles, whichever comes first.</T><View style={[s.row,{flexWrap:'wrap'}]}>{p.blockers.map((b:string)=><Badge key={b} label={b} tone="amber"/>)}</View><View style={[s.row,{flexWrap:'wrap'}]}>{matches.find((m:Match)=>m.id===p.match_id)&&<Button label="See evidence" kind="outline" onPress={()=>setDetail(matches.find((m:Match)=>m.id===p.match_id))}/>} {p.status!=='archived'&&<><Button label={p.status==='paused'?'Return to draft':'Pause plan'} kind="soft" disabled={busy===p.id} onPress={()=>action(p.id,p.status==='paused'?'resume':'pause')}/><Button label="Archive" kind="ghost" disabled={busy===p.id} onPress={()=>action(p.id,'archive')}/></>}</View></View>)}
  <View style={s.card}><T style={{fontFamily:'ManropeBold',fontSize:20}}>A visible trail, from idea to exit</T><View style={[s.row,{flexWrap:'wrap',gap:16}]}>{['Plan saved','Entry pending','Tracking pending','Exit pending'].map((x,i)=><View key={x} style={s.row}><Icon name={i===0?'check-circle':'circle'} size={16} color={i===0?C.green:C.muted}/><T style={{fontSize:12,color:C.muted}}>{x}</T>{i<3&&<Icon name="chevron-right" size={14} color={C.muted}/>}</View>)}</View><T style={{fontSize:12,color:C.muted}}>Only saved plans and their updates appear in the activity log. Nothing is marked filled until an execution engine provides a fill.</T></View>
 </Page>;
}

export function Agent(){
 const {state,matches,setFilters,setQuery,product}=useProduct();const [input,setInput]=useState(''),[answer,setAnswer]=useState('');
 function command(text:string){const q=text.trim().toLowerCase();setInput('');if(!q)return;
  if(/attention|ready|trade now/.test(q)){setAnswer(`${state?.current_matches||0} current setups. The latest source is ${dateText(state?.source_latest)}. Fresh market candles and an execution connection are needed before AutoTrade can run. Your ${product.plans.filter((p:any)=>p.status==='draft').length} saved drafts remain unexecuted.`);return;}
  if(/explain|return mean|how.*return/.test(q)){setAnswer('Past average return is the average net outcome of every eligible historical trade for that exact stock, pattern, timeframe and direction. It includes losing trades and 0.40% assumed costs. It is not a target or a forecast. Use See evidence to inspect the win rate, best and worst trades, holding time and rupee account.');return;}
  const f={...initialFilters};const tf=q.match(/\b(1h|4h|1d|1w)\b/);if(tf)f.timeframe=tf[1].toUpperCase();if(/bullish/.test(q))f.direction='bullish';if(/bearish/.test(q))f.direction='bearish';if(/2\s*[-–]\s*5/.test(q))f.band='2_5';if(/5\s*[-–]\s*10/.test(q))f.band='5_10';if(/0\.5\s*[-–]\s*1/.test(q))f.band='0.5_1';if(/1\s*[-–]\s*2/.test(q))f.band='1_2';if(/over 10|>\s*10/.test(q))f.band='over_10';
  const stock=matches.find((m:Match)=>new RegExp('(^|\\s)'+m.symbol.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'($|\\s)').test(q));
  const pattern=state?.patterns?.find((p:any)=>q.includes(p.name.toLowerCase())||q.includes(p.id.replaceAll('_',' ')));
  if(!tf&&!f.band&&f.direction==='all'&&!stock&&!pattern){setAnswer('I can open stock or pattern searches, select a timeframe and return range, explain the evidence, or check what needs attention. Try “bullish 4H”, “2–5% returns”, or a stock symbol. This preview uses guided commands, not a general chat model.');return;}
  setFilters(f);setQuery(stock?.symbol||pattern?.name||'');setAnswer('Your view is ready.');router.push('/');
 }
 return <Page><Heading eyebrow="KANIDA COPILOT" title="A little less noise.\nA lot more clarity." detail="A guided briefing grounded in your scanner and stock-level research."/>
  <View style={[s.card,{backgroundColor:C.dark,borderColor:C.dark,padding:28}]}><View style={s.row}><Orb size={80}/><View style={{flex:1,gap:5}}><T style={{fontFamily:'ManropeBold',fontSize:23,lineHeight:31,color:'white'}}>Here’s where we stand.</T><T style={{color:'#B2CBB9',fontSize:12}}>Evidence briefing · {dateText(state?.source_latest)} source</T></View></View><T style={{color:'#E2EBDF',fontSize:15,lineHeight:25}}>The engine covers {state?.universe?.toLocaleString()||'1,431'} stocks across 1H, 4H, daily and weekly charts. There are {matches.length} stored pattern setups to explore and {state?.current_matches||0} current setups.</T><View style={{height:1,backgroundColor:'#355447'}}/><T style={{color:'#BED5BD',fontSize:13}}>My next step: help you narrow the list, explain a stock’s evidence, then build a paper plan with explicit limits.</T></View>
  <View style={s.card}><T style={{fontFamily:'ManropeBold',fontSize:21}}>What would you like to focus on?</T><View style={[s.row,{flexWrap:'wrap'}]}>{['Bullish 4H','2–5% returns','What needs attention?','Explain the returns'].map(x=><Chip key={x} label={x} icon="arrow-up-right" onPress={()=>command(x)}/>)}</View><View style={s.row}><TextInput accessibilityLabel="Ask KANIDA" value={input} onChangeText={setInput} placeholder="Try a stock, pattern or timeframe…" placeholderTextColor={C.muted} onSubmitEditing={()=>command(input)} returnKeyType="send" style={[s.input,{flex:1}]}/><Button label="Go" icon="arrow-up" onPress={()=>command(input)} disabled={!input.trim()}/></View>{!!answer&&<View style={{padding:18,backgroundColor:C.soft,borderRadius:13}}><T style={{lineHeight:24}}>{answer}</T></View>}<T style={{fontSize:11,color:C.muted}}>Guided commands · no orders placed from chat</T></View>
  <T style={{fontFamily:'ManropeBold',fontSize:22}}>Activity, with receipts</T>{!product.events.length?<View style={s.card}><Rule n="✓" title="Research connected" text={`${matches.length} snapshots available. Create a paper plan to start your personal activity trail.`}/></View>:product.events.slice(0,20).map((e:any)=><View key={e.id} style={[s.card,{padding:19}]}><View style={s.between}><T style={{fontFamily:'InterSemi'}}>{e.title}</T><T style={{fontSize:10,color:C.muted}}>{dateText(e.created)}</T></View><T style={{fontSize:12,color:C.muted}}>{e.detail}</T></View>)}
 </Page>;
}

export function Connect(){
 const url=process.env.EXPO_PUBLIC_EXPO_URL||'';const code=useMemo(()=>{const qr=qrcode(0,'M');qr.addData(url);qr.make();return qr},[url]);const n=code.getModuleCount();let d='';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(code.isDark(r,c))d+=`M${c+4} ${r+4}h1v1h-1z`;
 return <Page><Heading eyebrow="KANIDA, WITH YOU" title="Meet your iPhone app." detail="Open the same KANIDA experience in Expo Go, with native navigation and touch controls."/><View style={[s.card,{alignItems:'center',padding:30}]}><Badge label="Expo SDK 57 · local preview"/><View style={{padding:12,backgroundColor:'white',borderRadius:15}}><Svg accessibilityLabel="Expo Go connection QR code" width={250} height={250} viewBox={`0 0 ${n+8} ${n+8}`}><Rect x="0" y="0" width={n+8} height={n+8} fill="white"/><Path d={d} fill={C.dark}/></Svg></View><T style={{fontFamily:'ManropeBold',fontSize:22,textAlign:'center'}}>Scan. Open. Explore.</T><View style={{maxWidth:470,gap:18}}><Rule n="1" title="Connect to the same Wi-Fi" text="Keep this computer and your iPhone on the same local network."/><Rule n="2" title="Install or update Expo Go" text="Use the current Expo Go app from the iPhone App Store."/><Rule n="3" title="Scan with your iPhone camera" text="Point the camera at this QR code, then choose Open in Expo Go. Keep the local servers running."/></View><Button label="Open in Expo Go" icon="smartphone" onPress={()=>Linking.openURL(url)}/><T selectable style={{fontSize:12,color:C.muted}}>{url}</T><T style={{fontSize:12,color:C.muted,textAlign:'center',maxWidth:520}}>Safari preview: {process.env.EXPO_PUBLIC_API_URL}. On a different Wi-Fi network, restart the preview script to refresh the local address.</T></View></Page>;
}
