import React,{useRef,useState} from 'react';
import {View,TextInput,Pressable,PanResponder,Animated,ScrollView} from 'react-native';
import {C,T,s,Button,Chip,Icon,Sheet} from './ui';
import {useProduct} from './context';

export function LabField({label,value,onChange,numeric=false}:any){return <View style={{gap:5,flex:1,minWidth:120}}><T style={{fontSize:11,color:C.muted}}>{label}</T><TextInput accessibilityLabel={label} value={String(value??'')} onChangeText={v=>onChange(numeric&&v!==''?Number(v):v)} keyboardType={numeric?'decimal-pad':'default'} placeholderTextColor={C.muted} style={[s.input,{minHeight:42,fontSize:13}]}/></View>}

function FlowCondition({block,index,definition,onChange,onMove,onRemove,last}:any){
 const y=useRef(new Animated.Value(0)).current,[dragging,setDragging]=useState(false);const move=useRef(onMove);move.current=onMove;
 const pan=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:()=>setDragging(true),onPanResponderMove:(_,g)=>y.setValue(g.dy),onPanResponderRelease:(_,g)=>{y.setValue(0);setDragging(false);move.current(Math.round(g.dy/112));},onPanResponderTerminate:()=>{y.setValue(0);setDragging(false)}})).current;
 return <View><Animated.View style={{transform:[{translateY:y}],zIndex:dragging?20:0,backgroundColor:dragging?C.soft:C.paper,borderWidth:1,borderColor:dragging?C.green:C.line,borderRadius:14,padding:13,gap:8}}><View style={s.row}><View {...pan.panHandlers} accessibilityLabel={`Drag condition ${index+1}`} style={{padding:10,touchAction:'none'} as any}><Icon name="grid" color={C.muted} size={17}/></View><View style={{flex:1}}><T style={{fontSize:10,color:C.green}}>CONDITION {index+1}</T><T style={{fontSize:13,fontFamily:'InterSemi'}}>{definition?.label||block.kind}</T></View><Pressable accessibilityRole="button" accessibilityLabel={`Move condition ${index+1} up`} disabled={!index} onPress={()=>onMove(-1)} style={{padding:6,opacity:index?1:.3}}><Icon name="arrow-up" size={16}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Move condition ${index+1} down`} disabled={last} onPress={()=>onMove(1)} style={{padding:6,opacity:last?.3:1}}><Icon name="arrow-down" size={16}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Remove condition ${index+1}`} onPress={onRemove} style={{padding:6}}><Icon name="x" size={17}/></Pressable></View>{block.kind==='pattern'?<T style={{color:C.green,paddingLeft:12}}>{String(block.value).replace(/_/g,' ')}</T>:<View style={[s.row,{paddingLeft:12}]}><TextInput accessibilityLabel={`${definition?.label||block.kind} value`} style={[s.input,{minHeight:38,width:95}]} keyboardType="decimal-pad" value={String(block.value)} onChangeText={v=>onChange({...block,value:v===''?'':Number(v)})}/><T style={{fontSize:12,color:C.muted}}>{definition?.unit}</T></View>}</Animated.View><View style={{height:22,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-down" size={16} color={C.green}/></View></View>
}

export function StrategyFlow({spec,caps,onChange,highlight=[]}:any){
 const p=useProduct();const [library,setLibrary]=useState(false),[settings,setSettings]=useState(false),[section,setSection]=useState('entry'),[term,setTerm]=useState('');
 if(!spec)return null;
 const definitions=Object.fromEntries((caps?.conditions||[]).map((v:any)=>[v.kind,v]));
 function change(patch:any){onChange({...spec,...patch})}function exits(patch:any){change({exit:{...spec.exit,...patch}})}
 function move(index:number,delta:number){const blocks=[...spec.conditions],to=Math.max(0,Math.min(blocks.length-1,index+delta));const [item]=blocks.splice(index,1);blocks.splice(to,0,item);change({conditions:blocks})}
 function add(kind:string,value:any){change({conditions:[...spec.conditions,{id:'c'+Date.now(),kind,value}]});setLibrary(false)}
 return <View style={{gap:0}}><View style={[s.between,{marginBottom:16}]}><View style={{flex:1}}><T style={{fontFamily:'ManropeBold',fontSize:21}}>Your strategy, made visible.</T><T style={{fontSize:12,color:C.muted}}>Drag a handle to reorder. Every visible rule is tested.</T></View><Button label="Settings" kind="outline" icon="sliders" onPress={()=>setSettings(true)}/></View>
 <Pressable accessibilityRole="button" accessibilityLabel="Edit strategy universe" onPress={()=>{setSection('universe');setSettings(true)}} style={[s.card,{borderColor:'#28634F',padding:16,gap:5}]}><View style={s.between}><T style={{fontSize:10,color:C.green,letterSpacing:1.5}}>01 · CHOOSE THE MARKET</T><Icon name="edit-2" size={15} color={C.muted}/></View><T style={{fontFamily:'InterSemi',fontSize:17}}>{spec.symbols?.length?spec.symbols.join(', '):caps?.universes?.find((u:any)=>u.value===spec.universe)?.label||'All available stocks'}</T><T style={{fontSize:12,color:C.muted}}>{spec.sector||'All sectors'} · Daily · CNC delivery</T></Pressable><View style={{height:26,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-down" color={C.green}/></View>
 <View style={[s.between,{marginBottom:10}]}><T style={{fontSize:10,color:C.muted,letterSpacing:1.5}}>02 · QUALIFY THE ENTRY</T><Pressable accessibilityRole="button" accessibilityLabel="Toggle all or any entry conditions" onPress={()=>change({join:spec.join==='all'?'any':'all'})}><T style={{color:C.green,fontSize:12}}>{spec.join==='all'?'ALL conditions (AND)':'ANY condition (OR)'}</T></Pressable></View>
 {spec.conditions.map((b:any,i:number)=><View key={b.id+'-'+i}>{highlight.includes(b.kind)&&<T style={{color:C.amber,fontSize:11,padding:5}}>Added by KANIDA · inspect its measured effect in Evidence</T>}<FlowCondition block={b} index={i} definition={definitions[b.kind]} last={i===spec.conditions.length-1} onMove={(delta:number)=>move(i,delta)} onChange={(block:any)=>change({conditions:spec.conditions.map((old:any,j:number)=>j===i?block:old)})} onRemove={()=>change({conditions:spec.conditions.filter((_:any,j:number)=>j!==i)})/></View>)}
 <Button label="Add a condition" icon="plus" kind="outline" onPress={()=>setLibrary(true)}/><View style={{height:26,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-down" color={C.green}/></View>
 <Pressable accessibilityRole="button" accessibilityLabel="Edit allocation and ranking" onPress={()=>{setSection('capital');setSettings(true)}} style={[s.card,{padding:16,gap:5}]}><T style={{fontSize:10,color:C.green,letterSpacing:1.5}}>03 · RANK & ALLOCATE</T><T style={{fontFamily:'InterSemi'}}>Buy up to {spec.max_positions} stocks</T><T style={{fontSize:12,color:C.muted}}>{spec.allocation_pct}% per position · ranked by {spec.ranking} · review {spec.rebalance}</T></Pressable><View style={{height:26,alignItems:'center',justifyContent:'center'}}><Icon name="arrow-down" color={C.green}/></View>
 <Pressable accessibilityRole="button" accessibilityLabel="Edit strategy exits" onPress={()=>{setSection('exit');setSettings(true)}} style={[s.card,{padding:16,gap:5}]}><T style={{fontSize:10,color:C.amber,letterSpacing:1.5}}>04 · EXIT & PROTECT</T><T style={{fontFamily:'InterSemi'}}>Target +{spec.exit.target}% · Stop {spec.exit.stop}{spec.exit.stop_kind==='atr'?' ATR':'%'}</T><T style={{fontSize:12,color:C.muted}}>Hold up to {spec.exit.hold} trading days{spec.exit.trailing?` · ${spec.exit.trailing}% trailing stop`:''}{spec.exit.disqualify?' · exit when rules no longer qualify':''}</T></Pressable>
 <T style={{fontSize:11,lineHeight:18,color:C.muted,marginTop:14}}>Entry at the next open after a completed daily signal. Moving blocks changes presentation; AND/OR controls entry logic. No code or hidden rule is executed.</T>
 <Sheet visible={library} title="Condition library" subtitle="Use available data. Missing datasets are identified below." onClose={()=>setLibrary(false)}><TextInput accessibilityLabel="Search strategy conditions" value={term} onChangeText={setTerm} placeholder="RSI, volume, pattern…" placeholderTextColor={C.muted} style={s.input}/>{caps?.conditions?.filter((b:any)=>b.label.toLowerCase().includes(term.toLowerCase())).map((b:any)=><View key={b.kind} style={{gap:5}}>{b.kind==='pattern'?<><T style={{fontFamily:'InterSemi'}}>Chart patterns</T><View style={[s.row,{flexWrap:'wrap'}]}>{p.state?.patterns?.map((x:any)=><Chip key={x.id} label={x.name} onPress={()=>add('pattern',x.id)}/>)}</View></>:<Button label={b.label} icon="plus" kind="outline" onPress={()=>add(b.kind,b.value)}/>}</View>)}<T style={{fontFamily:'InterSemi',color:C.amber}}>Needs additional data</T>{Object.entries(caps?.unavailable||{}).map(([key,value])=><View key={key} style={{gap:3}}><T style={{fontSize:13}}>{key.replace(/_/g,' ')}</T><T style={{fontSize:12,color:C.muted}}>{String(value)}</T></View>)}</Sheet>
 <Sheet visible={settings} title="Strategy settings" subtitle="Changes create a new draft. Saved research remains tied to its original rules." onClose={()=>setSettings(false)} footer={<Button label="Use these settings" onPress={()=>setSettings(false)}/>}><View style={[s.row,{flexWrap:'wrap'}]}>{['universe','entry','capital','exit','evidence'].map(v=><Chip key={v} label={v[0].toUpperCase()+v.slice(1)} active={section===v} onPress={()=>setSection(v)}/>)}</View>
 {section==='universe'&&<><LabField label="Strategy name" value={spec.name} onChange={(v:string)=>change({name:v})}/><LabField label="Stocks (comma separated; blank = selected universe)" value={spec.symbols.join(', ')} onChange={(v:string)=>change({symbols:v.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean)})}/><View style={[s.row,{flexWrap:'wrap'}]}><Chip label="All available" active={!spec.universe} onPress={()=>change({universe:''})}/>{caps?.universes?.map((u:any)=><Chip key={u.value} label={`${u.label} · ${u.count}`} active={spec.universe===u.value} onPress={()=>change({universe:u.value})}/>)}</View><T style={{fontSize:12,color:C.amber}}>Counts reflect supplied labels, not complete historical index lists. Market-cap, quality and Nifty 1000 filters need additional data.</T><T>Sector</T><View style={[s.row,{flexWrap:'wrap'}]}><Chip label="All sectors" active={!spec.sector} onPress={()=>change({sector:''})}/>{caps?.sectors?.map((v:any)=><Chip key={v.value} label={v.value} active={spec.sector===v.value} onPress={()=>change({sector:v.value})}/>)}</View></>}
 {section==='entry'&&<><T>Combine entry blocks</T><View style={s.row}><Chip label="All (AND)" active={spec.join==='all'} onPress={()=>change({join:'all'})}/><Chip label="Any (OR)" active={spec.join==='any'} onPress={()=>change({join:'any'})}/></View><T>Prioritize qualifying stocks</T><View style={[s.row,{flexWrap:'wrap'}]}>{['momentum','liquidity','symbol'].map(v=><Chip key={v} label={v} active={spec.ranking===v} onPress={()=>change({ranking:v})}/>)}</View><T>Review schedule</T><View style={s.row}>{['daily','weekly','monthly'].map(v=><Chip key={v} label={v} active={spec.rebalance===v} onPress={()=>change({rebalance:v})}/>)}</View><T style={s.muted}>Weekly/monthly reviews happen on the first available session of the new period, with entry at the next open. Exits and risk stops are monitored every daily candle.</T></>}
 {section==='capital'&&<><LabField label="Starting capital (₹)" value={spec.capital} numeric onChange={(v:number)=>change({capital:v})}/><LabField label="Maximum open stocks" value={spec.max_positions} numeric onChange={(v:number)=>change({max_positions:v})}/><LabField label="Maximum allocation per stock (%)" value={spec.allocation_pct} numeric onChange={(v:number)=>change({allocation_pct:v})}/><LabField label="Risk per trade (%)" value={spec.risk_pct} numeric onChange={(v:number)=>change({risk_pct:v})}/><LabField label="Round-trip fees (basis points)" value={spec.fee_bps} numeric onChange={(v:number)=>change({fee_bps:v})}/><LabField label="Slippage per side (basis points)" value={spec.slippage_bps} numeric onChange={(v:number)=>change({slippage_bps:v})}/><T style={s.muted}>Whole shares, shared available cash, no leverage. 100 basis points = 1%. Fees are assumptions, not a broker tariff.</T></>}
 {section==='exit'&&<><View style={s.row}><Chip label="Percentage stop" active={spec.exit.stop_kind==='percent'} onPress={()=>exits({stop_kind:'percent'})}/><Chip label="ATR stop" active={spec.exit.stop_kind==='atr'} onPress={()=>exits({stop_kind:'atr',stop:2})}/></View><LabField label={spec.exit.stop_kind==='atr'?'Stop distance (ATR)':'Stop distance (%)'} value={spec.exit.stop} numeric onChange={(v:number)=>exits({stop:v})}/><LabField label="Profit target (%)" value={spec.exit.target} numeric onChange={(v:number)=>exits({target:v})}/><LabField label="Maximum holding (trading days)" value={spec.exit.hold} numeric onChange={(v:number)=>exits({hold:v})}/><LabField label="Trailing stop (%; 0 = off)" value={spec.exit.trailing} numeric onChange={(v:number)=>exits({trailing:v})}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:spec.exit.disqualify}} onPress={()=>exits({disqualify:!spec.exit.disqualify})}><T>{spec.exit.disqualify?'☑':'☐'} Exit if entry conditions no longer qualify at review</T></Pressable><T style={s.muted}>Trailing stops use highs from earlier completed candles. An ambiguous stop/target candle is resolved to the stop.</T></>}
 {section==='evidence'&&<><View style={s.row}><LabField label="Start date (YYYY-MM-DD)" value={spec.start} onChange={(v:string)=>change({start:v})}/><LabField label="End date (YYYY-MM-DD)" value={spec.end} onChange={(v:string)=>change({end:v})}/></View><LabField label="Annual return objective (%)" value={spec.objectives.cagr} numeric onChange={(v:number)=>change({objectives:{...spec.objectives,cagr:v}})}/><LabField label="Maximum drawdown objective (%)" value={spec.objectives.drawdown} numeric onChange={(v:number)=>change({objectives:{...spec.objectives,drawdown:v}})}/><LabField label="Minimum historical trades" value={spec.min_trades} numeric onChange={(v:number)=>change({min_trades:v})}/><LabField label="Rolling learning window (months)" value={spec.train_months} numeric onChange={(v:number)=>change({train_months:v})}/><LabField label="Following test window (months)" value={spec.test_months} numeric onChange={(v:number)=>change({test_months:v})}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:spec.objectives.beat_nifty}} onPress={()=>change({objectives:{...spec.objectives,beat_nifty:!spec.objectives.beat_nifty}})}><T>{spec.objectives.beat_nifty?'☑':'☐'} Require outperformance vs Nifty 50</T></Pressable><T style={s.muted}>Objectives are tests, not promises. The final 20% of dates is excluded from candidate selection. A five-trade minimum does not imply strong confidence.</T></>}
 </Sheet></View>
}
