import React,{useState,useEffect} from 'react';
import {View,Pressable,ScrollView,Platform,Share} from 'react-native';
import Svg,{Path,Line,Rect,Text as SvgText,G} from 'react-native-svg';
import {C,T,s,Button,Chip,Sheet,Badge,Loading} from './ui';
import {api,money,pct,dateText} from './model';
import {EquityPlot,HistoryChart,Metric} from './ReplayStudio';

function RuleChart({bundle,cursor}:any){
 const [width,setWidth]=useState(540);if(bundle.shape)return <HistoryChart bundle={bundle} cursor={cursor} height={260}/>;
 const visible=bundle.bars.slice(0,cursor+1);if(!visible.length)return null;
 const W=Math.max(270,width),H=270,L=10,R=58,B=35,Tp=20;const prices=visible.flatMap((b:any)=>[b.low,b.high]);const low=Math.min(...prices),high=Math.max(...prices),pad=(high-low)*.12||1;
 const step=(W-L-R)/Math.max(30,visible.length);const x=(i:number)=>L+(i+.5)*step,y=(v:number)=>Tp+(high+pad-v)/(high-low+pad*2)*(H-B-Tp);const tr=bundle.trade;
 return <View onLayout={e=>setWidth(e.nativeEvent.layout.width)} style={{gap:8}}><T style={{fontSize:12,color:C.green}}>{cursor>=bundle.signal_index?'Rules qualified at this close':'Replaying the information available then'}</T><Svg width="100%" height={H} viewBox={`0 0 ${W} ${H}`}>
 {[0,1,2,3].map(i=>{const v=low+(high-low)*i/3;return <G key={i}><Line x1={L} x2={W-R} y1={y(v)} y2={y(v)} stroke={C.line}/><SvgText x={W-R+7} y={y(v)+4} fontSize={11} fill={C.muted}>{Math.round(v).toLocaleString('en-IN')}</SvgText></G>})}
 {visible.map((b:any,i:number)=><G key={i}><Line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={b.close>=b.open?C.green:C.red}/><Rect x={x(i)-step*.28} y={Math.min(y(b.open),y(b.close))} width={Math.max(.7,step*.56)} height={Math.max(1,Math.abs(y(b.close)-y(b.open)))} fill={b.close>=b.open?C.green:C.red}/></G>)}
 {bundle.overlays?.map((o:any,k:number)=><Path key={o.name} d={o.values.slice(0,cursor+1).map((v:number|null,i:number)=>v==null?'':`${i===0||o.values[i-1]==null?'M':'L'}${x(i)},${y(v)}`).join(' ')} stroke={k%2?C.amber:'#9AC9FF'} strokeWidth={1.6} fill="none"/>)}
 {cursor>=tr.entry_chart_index&&<><Line x1={x(tr.entry_chart_index)} x2={x(tr.entry_chart_index)} y1={Tp} y2={H-B} stroke={C.amber} strokeDasharray="3 3"/><SvgText x={Math.min(W-R-42,x(tr.entry_chart_index)+4)} y={30} fill={C.amber} fontSize={11}>Entry</SvgText></>}
 {cursor>=bundle.signal_index&&[tr.stop,tr.target].filter((v:any)=>v!=null&&v>=low-pad&&v<=high+pad).map((v:number,i:number)=><Line key={i} x1={x(bundle.signal_index)} x2={W-R} y1={y(v)} y2={y(v)} stroke={i?C.green:C.red} strokeDasharray="5 4"/>)}
 <SvgText x={L} y={H-10} fontSize={11} fill={C.muted}>{dateText(visible[0].time)}</SvgText><SvgText x={W-R} y={H-10} textAnchor="end" fontSize={11} fill={C.muted}>{dateText(visible.at(-1).end)}</SvgText>
 </Svg><T style={{fontSize:12,color:C.muted}}>{dateText(visible.at(-1).end)} · Close {money(visible.at(-1).close,2)}</T>{bundle.overlays?.length>0&&<T style={{fontSize:11,color:'#9AC9FF'}}>{bundle.overlays.map((o:any)=>o.name).join(' · ')}</T>}</View>
}

export function StrategyTradeReplay({jobId,variant,trade,onClose,account}:any){
 const [bundle,setBundle]=useState<any>(null),[error,setError]=useState(''),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{let alive=true;setBundle(null);setError('');setPlaying(false);if(trade)api(`/api/lab/chart?id=${jobId}&variant=${variant}&trade=${encodeURIComponent(trade.id)}`).then(v=>{if(alive){setBundle(v);setCursor(Math.max(0,v.signal_index-15))}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[trade?.id,jobId,variant]);
 useEffect(()=>{if(!playing||!bundle)return;const timer=setTimeout(()=>{if(cursor>=bundle.bars.length-1)setPlaying(false);else setCursor(cursor+1)},150);return()=>clearTimeout(timer)},[playing,cursor,bundle]);
 const time=bundle?.bars?.[cursor]?.end;
 return <Sheet visible={!!trade} title={`${trade?.symbol||''} · Historical evidence`} subtitle={trade?`${dateText(trade.signal_time)} signal → ${dateText(trade.exit_time)} exit`:''} wide onClose={onClose}>{error?<T style={{color:C.red}}>{error}</T>:!bundle?<Loading/>:<><RuleChart bundle={bundle} cursor={cursor}/><View style={[s.row,{flexWrap:'wrap'}]}><Button label={playing?'Pause replay':'Play historical instance'} icon={playing?'pause':'play'} onPress={()=>{if(cursor>=bundle.bars.length-1)setCursor(Math.max(0,bundle.signal_index-15));setPlaying(!playing)}}/><Button label="Show outcome" kind="outline" onPress={()=>{setPlaying(false);setCursor(bundle.bars.length-1)}}/></View><View style={[s.row,{flexWrap:'wrap'}]}><Metric label="Net trade P&L" value={cursor>=trade.exit_index-(trade.signal_index-bundle.signal_index)?money(trade.net_pnl,2):'Exit not yet reached'}/><Metric label="Entry" value={money(trade.entry,2)}/><Metric label="Shares" value={trade.quantity}/><Metric label="Holding time" value={`${trade.holding_bars} trading days`}/></View><T style={{fontSize:12,color:C.muted}}>Signal values: {Object.entries(bundle.features||{}).map(([k,v])=>`${k.replace(/_/g,' ')} ${v??'unavailable'}`).join(' · ')}</T><EquityPlot curve={account?.curve||[]} time={time} height={220}/></>}</Sheet>
}

async function exportEvidence(job:any){const r=job.result;const doc=JSON.stringify({research_id:job.id,version:r.version,run:r.run,spec:r.spec,split:r.split,rows:r.rows,walkforward:r.walkforward,assumptions:r.assumptions,benchmark_source:r.benchmark_source},null,2);if(Platform.OS==='web'){const url=URL.createObjectURL(new Blob([doc],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`kanida-strategy-${job.id.slice(0,8)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}else await Share.share({message:doc,title:'KANIDA strategy evidence'})}

export function StrategyEvidence({job,selected,onSelect,onUse,onPrepare}:any){
 const r=job.result;const [tab,setTab]=useState('Overview'),[segment,setSegment]=useState('holdout'),[trade,setTrade]=useState<any>(null),[count,setCount]=useState(50),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(0);
 const row=r.rows.find((v:any)=>v.id===selected)||r.rows[0],account=r.accounts[row.id],stats=row[segment]||row.holdout;
 useEffect(()=>{setFrame(0);setPlaying(false);setTrade(null);setCount(50)},[job.id,row.id]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(frame>=account.curve.length-1)setPlaying(false);else setFrame(Math.min(account.curve.length-1,frame+Math.max(1,Math.floor(account.curve.length/200))))},100);return()=>clearTimeout(timer)},[playing,frame,account]);
 const metric=(label:string,v:any)=> <Metric key={label} label={label} value={v}/>;
 return <View style={{gap:16}}><View style={[s.between,{flexWrap:'wrap'}]}><View style={{flex:1}}><T style={{fontFamily:'ManropeBold',fontSize:22}}>The evidence has the final word.</T><T style={{fontSize:12,color:C.muted}}>{r.variation_count} actual variations · {job.symbols.length} stocks · {dateText(r.spec.start)} – {dateText(r.spec.end)}</T></View><Button label="Export evidence" icon="download" kind="ghost" onPress={()=>exportEvidence(job)}/></View>
 <View style={{borderLeftWidth:3,borderColor:r.improvement_supported?C.green:C.amber,padding:14,backgroundColor:r.improvement_supported?C.soft:C.amberBg,gap:6}}><T style={{fontFamily:'InterSemi',color:r.improvement_supported?C.green:C.amber}}>{r.improvement_supported?'An improvement survived the final test':'No improvement established'}</T><T style={{fontSize:13,lineHeight:21}}>{r.verdict}</T></View>
 <View style={[s.row,{flexWrap:'wrap'}]}>{['conservative','balanced','aggressive'].map(key=>{const id=r.choices[key];return <Chip key={key} label={`${key[0].toUpperCase()+key.slice(1)}${id===row.id?' ✓':''}`} active={id===row.id} onPress={()=>id&&onSelect(id)}/>})}<Chip label="Original" active={row.id==='original'} onPress={()=>onSelect('original')}/></View><T style={{fontSize:11,color:C.muted}}>Profiles were selected on the discovery period. They may identify the same candidate. They are historical risk profiles, not forecasts.</T>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:6}}>{['Overview','Compare','Why & where','Replay','Walk-forward','Rules & data'].map(v=><Chip key={v} label={v} active={tab===v} onPress={()=>setTab(v)}/>)}</ScrollView>
 {tab==='Overview'&&<><View style={s.between}><View style={{flex:1}}><T style={{fontFamily:'InterSemi',fontSize:17}}>{row.name}</T><T style={{fontSize:12,color:C.muted}}>{row.change}</T></View><Badge label={row.meets_requested_objective?'FINAL TEST MET OBJECTIVE':'OBJECTIVE NOT ESTABLISHED'} tone={row.meets_requested_objective?'green':'amber'}/></View><View style={[s.row,{flexWrap:'wrap'}]}>{[['holdout','Final test'],['discovery','Discovery'],['full','Full history']].map(([key,label])=><Chip key={key} label={label} active={segment===key} onPress={()=>setSegment(key)}/>)}</View><T style={{fontSize:12,color:C.muted}}>{segment==='holdout'?`${dateText(r.split.holdout_start)} → ${dateText(r.split.holdout_end)} · Excluded from selection.`:segment==='discovery'?`${dateText(r.split.discovery_start)} → ${dateText(r.split.discovery_end)} · Used to select profiles.`:'Exploratory full-history results include the selection period.'}</T>
 <View style={[s.row,{flexWrap:'wrap',gap:22}]}>{metric('Annualized return',pct(stats.cagr))}{metric('Nifty 50 annualized',pct(stats.benchmark_cagr))}{metric('Total return',pct(stats.return_pct))}{metric('Excess total return',stats.excess_return_pct==null?'—':`${stats.excess_return_pct.toFixed(2)} pp`)}{metric('Maximum drawdown',pct(-stats.max_drawdown_pct))}{metric('Volatility / year',pct(stats.volatility_pct))}{metric('Sharpe · zero risk-free',stats.sharpe?.toFixed(2)??'—')}{metric('Wins / trades',`${stats.wins} / ${stats.trades}`)}{metric('Win rate',pct(stats.win_rate))}{metric('Average winner',pct(stats.average_win_pct))}{metric('Average loser',pct(stats.average_loss_pct))}{metric('Average per trade',pct(stats.average_return_pct))}{metric('Ending account',money(stats.ending_equity,2))}{metric('Assumed fees',money(stats.total_costs,2))}</View><View style={s.line}/><T style={{fontFamily:'InterSemi'}}>Full-history account replay</T><EquityPlot curve={account.curve} benchmark={r.benchmark} time={playing||frame>0?account.curve[frame]?.time:undefined} height={230}/><View style={[s.row,{flexWrap:'wrap'}]}><Button label={playing?'Pause account replay':'Play account replay'} icon={playing?'pause':'play'} kind="outline" onPress={()=>{if(frame>=account.curve.length-1)setFrame(0);setPlaying(!playing)}}/><T style={{fontSize:11,color:C.muted}}>Solid = strategy · dashed = Nifty 50 price index</T></View><View style={[s.row,{flexWrap:'wrap'}]}><Button label="Inspect this strategy flow" kind="outline" onPress={()=>onUse(row)}/><Button label="Prepare paper portfolio" icon="arrow-up-right" onPress={()=>onPrepare(row)}/></View></>}
 {tab==='Compare'&&<><T style={{fontSize:12,color:C.muted}}>Candidate changes and paired outcomes. Selection used earlier data; final results are displayed for diagnosis, not for choosing another winner.</T><ScrollView horizontal><View style={{minWidth:680}}><View style={[s.row,{padding:12,backgroundColor:C.paper}]}>{['Candidate','Earlier CAGR','Final CAGR','Final max DD','Final trades'].map((v,i)=><T key={v} style={{width:i===0?215:105,fontSize:11,color:C.muted}}>{v}</T>)}</View>{r.rows.map((v:any)=><Pressable key={v.id} accessibilityRole="button" accessibilityLabel={`Inspect candidate ${v.name}`} onPress={()=>onSelect(v.id)} style={[s.row,{padding:12,borderBottomWidth:1,borderColor:C.line,backgroundColor:row.id===v.id?C.soft:'transparent'}]}><T style={{width:215,fontSize:12,color:row.id===v.id?C.green:C.ink}}>{v.name}</T><T style={{width:105,fontSize:12}}>{pct(v.discovery.cagr)}</T><T style={{width:105,fontSize:12}}>{pct(v.holdout.cagr)}</T><T style={{width:105,fontSize:12}}>{pct(-v.holdout.max_drawdown_pct)}</T><T style={{width:105,fontSize:12}}>{v.holdout.trades}</T></Pressable>)}</View></ScrollView><T style={{fontFamily:'InterSemi'}}>Annual performance · {row.name}</T>{row.full.annual.map((v:any)=><View key={v.year} style={s.between}><T>{v.year}{v.partial?' · partial year':''}</T><T style={{color:v.return_pct>=0?C.green:C.red}}>{pct(v.return_pct)}</T></View>)}<T style={{fontSize:12,color:C.muted}}>Partial first and last years are not directly comparable to full calendar years.</T></>}
 {tab==='Why & where'&&<><T style={{fontFamily:'InterSemi'}}>What the original lost money on</T>{r.accounts.original.diagnostics.observations.map((v:string)=><T key={v} style={{fontSize:13,lineHeight:22}}>{v}</T>)}<T style={{fontFamily:'InterSemi'}}>Where {row.name.toLowerCase()} worked and failed</T>{account.diagnostics.regimes.map((v:any)=><View key={v.regime} style={s.card}><View style={s.between}><T>{v.regime} market</T><T style={{color:v.net_pnl>=0?C.green:C.red}}>{money(v.net_pnl,2)}</T></View><T style={{fontSize:12,color:C.muted}}>{v.trades} trades · {pct(v.win_rate)} win rate · {pct(v.average_return_pct)} average / trade</T></View>)}<T style={{fontSize:11,color:C.muted}}>{account.diagnostics.definition}</T><T style={{fontFamily:'InterSemi'}}>Typical winning and losing paths</T><View style={[s.row,{flexWrap:'wrap'}]}>{[true,false].map(win=>{const list=account.trades.filter((t:any)=>win?t.net_pnl>0:t.net_pnl<0).sort((a:any,b:any)=>a.net_return_pct-b.net_return_pct);const typical=list[Math.floor(list.length/2)];return <Button key={String(win)} label={win?'Replay median winner':'Replay median loser'} disabled={!typical} kind="outline" onPress={()=>setTrade(typical)}/>})}</View><T style={{fontSize:12,color:C.muted}}>Historical frequency is not a probability guarantee. Regime comparisons describe this dataset and rule family.</T></>}
 {tab==='Replay'&&<><T style={{fontFamily:'InterSemi'}}>Every executed instance · {account.trades.length} trades</T><T style={{fontSize:12,color:C.muted}}>Open a trade to replay completed candles, signal values, entry and the account path. Losing trades stay visible.</T>{account.trades.slice(0,count).map((t:any)=><Pressable key={t.id} accessibilityRole="button" accessibilityLabel={`Replay ${t.symbol} ${t.entry_time.slice(0,10)}`} onPress={()=>setTrade(t)} style={[s.between,{borderBottomWidth:1,borderColor:C.line,paddingVertical:12}]}><View style={{flex:1}}><T style={{fontFamily:'InterSemi'}}>{t.symbol}</T><T style={{fontSize:11,color:C.muted}}>{dateText(t.entry_time)} → {dateText(t.exit_time)} · {t.holding_bars} trading days</T></View><View><T style={{color:t.net_pnl>=0?C.green:C.red}}>{money(t.net_pnl,2)}</T><T style={{fontSize:11,color:C.muted}}>{t.quantity} shares · {t.exit_reason.replace(/_/g,' ')}</T></View></Pressable>)}{count<account.trades.length&&<Button label="Show 50 more trades" kind="outline" onPress={()=>setCount(count+50)}/>}<T style={{fontSize:12,color:C.muted}}>{account.skipped.length} additional entries were skipped by capital or position limits.</T></>}
 {tab==='Walk-forward'&&<><T style={{fontFamily:'InterSemi'}}>Learn earlier. Freeze. Test later.</T><T style={{fontSize:12,color:C.muted}}>At each boundary the engine selects from the declared variations using only earlier completed holding horizons. One shared account continues across test windows.</T>{r.walkforward.metrics?<><View style={[s.row,{flexWrap:'wrap',gap:18}]}>{metric('Test-only CAGR',pct(r.walkforward.metrics.cagr))}{metric('Nifty CAGR, same dates',pct(r.walkforward.metrics.benchmark_cagr))}{metric('Maximum drawdown',pct(-r.walkforward.metrics.max_drawdown_pct))}{metric('Trades',r.walkforward.metrics.trades)}</View><EquityPlot curve={r.walkforward.curve} height={230}/></>:<T style={{color:C.amber}}>{r.walkforward.note}</T>}{r.walkforward.folds.map((f:any,i:number)=><View key={i} style={{gap:4,borderBottomWidth:1,borderColor:C.line,paddingVertical:12}}><T>{dateText(f.start)} → {dateText(f.end)}</T><T style={{fontSize:12,color:C.green}}>{f.selected?`${r.rows.find((v:any)=>v.id===f.selected.id)?.name} · ${f.selected.samples} learning trades`:'No qualifying learning rule · stay in cash'}</T><T style={{fontSize:11,color:C.muted}}>Learned {f.train_start} → {f.train_end}; potential holding horizons purged at the boundary.</T></View>)}</>}
 {tab==='Rules & data'&&<><T style={{fontFamily:'InterSemi'}}>Reproducible evidence</T><T style={{fontSize:12,color:C.muted}}>Research {job.id.slice(0,10)} · {r.version} · Source {r.run}</T>{r.assumptions.map((v:string)=><T key={v} style={{fontSize:12,lineHeight:20,color:C.muted}}>• {v}</T>)}<T style={{fontFamily:'InterSemi'}}>History coverage</T><T style={{fontSize:12,color:C.amber}}>{r.coverage.filter((v:any)=>v.full_requested_period).length} / {r.coverage.length} stocks span the entire requested period. {r.coverage.reduce((n:number,v:any)=>n+v.large_moves,0)} daily moves exceed 35%; inspect corporate actions before relying on absolute performance.</T>{r.coverage.slice(0,30).map((v:any)=><T key={v.symbol} style={{fontSize:12,color:C.muted}}>{v.symbol} · {v.first} → {v.last} · {v.bars} candles</T>)}<T style={{fontSize:12,color:C.muted}}>Benchmark: {r.benchmark_source.name} · dividends excluded · frozen digest {r.benchmark_source.sha256.slice(0,16)}</T></>}
 <StrategyTradeReplay jobId={job.id} variant={row.id} trade={trade} account={account} onClose={()=>setTrade(null)}/></View>
}
