import React from 'react';
import {View,Pressable,ScrollView,useWindowDimensions} from 'react-native';
import {Slot,router,usePathname} from 'expo-router';
import {StatusBar} from 'expo-status-bar';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import Svg,{Path,Circle} from 'react-native-svg';
import {C,T,s,Icon,Button} from './ui';
import {useProduct} from './context';
import {ProductSheets} from './Sheets';
export function AgentMark({size=36,color=C.green}:any){return <Svg width={size} height={size} viewBox="0 0 40 40"><Circle cx="20" cy="20" r="18" fill="none" stroke={color} strokeOpacity=".35" strokeWidth=".7"/><Path d="M20 6L23 17L34 20L23 23L20 34L17 23L6 20L17 17Z" fill={color}/><Circle cx="20" cy="20" r="3" fill={C.bg}/><Path d="M10 10L15 14M27 27L30 30M30 10L27 13M10 30L13 27" stroke={color} strokeWidth=".8"/></Svg>;}
const tabs=[['/','Discover','aperture'],['/watch','My watch','eye'],['/autotrade','AutoTrade','zap']];
export function TraderShell(){const {width}=useWindowDimensions();const mobile=width<850;const path=usePathname();const inset=useSafeAreaInsets();const {toast,error,refresh,product}=useProduct();
 function tab(url:string,label:string,icon:string){const active=path===url;return <Pressable key={url} accessibilityRole="link" accessibilityLabel={label} accessibilityState={{selected:active}} onPress={()=>router.push(url as any)} style={({pressed})=>[{minHeight:48,flex:mobile?1:undefined,flexDirection:mobile?'column':'row',justifyContent:'center',alignItems:'center',gap:mobile?5:9,paddingHorizontal:mobile?4:19,borderRadius:9,backgroundColor:!mobile&&active?C.paper:'transparent',opacity:pressed?.6:1}]}><Icon name={icon} color={active?C.green:C.muted} size={mobile?22:16}/><T style={{fontSize:mobile?10:12,fontFamily:'InterSemi',color:active?C.green:C.muted}}>{label==='Trader Agent'&&mobile?'Agent':label}</T>{!mobile&&url==='/watch'&&!!product.watchlist?.length&&<T style={{fontSize:10,color:C.green}}>{product.watchlist.length}</T>}</Pressable>}
 return <View style={{flex:1,backgroundColor:C.bg}}><StatusBar style="light"/><View style={{backgroundColor:C.bg,borderBottomWidth:1,borderColor:C.line,paddingTop:inset.top}}><View style={[s.between,{width:'100%',maxWidth:1500,alignSelf:'center',paddingHorizontal:mobile?18:34,height:mobile?68:82}]}><Pressable accessibilityRole="link" accessibilityLabel="KANIDA home" onPress={()=>router.push('/welcome')} style={[s.row,{gap:12}]}><AgentMark size={mobile?34:40}/><View><T style={{fontFamily:'InterMedium',fontSize:mobile?19:22,letterSpacing:3}}>KANIDA<T style={{fontSize:13,color:C.muted,letterSpacing:1}}>.AI</T></T>{!mobile&&<T style={{fontSize:9,lineHeight:14,letterSpacing:1.5,color:C.muted}}>YOUR TRADER AGENT</T>}</View></Pressable>{!mobile&&<View style={s.row}>{tabs.map(([u,l,i])=>tab(u,l,i))}</View>}<View style={s.row}><View style={[s.row,{gap:5}]}><View style={{width:5,height:5,borderRadius:3,backgroundColor:C.green}}/><T style={{fontSize:10,color:C.muted}}>Preview</T></View><Pressable accessibilityRole="button" accessibilityLabel="Open on iPhone" onPress={()=>router.push('/connect')} style={{padding:12}}><Icon name="smartphone" color={C.muted} size={18}/></Pressable></View></View></View>
 {!!error&&<View style={[s.between,{padding:12,backgroundColor:C.amberBg}]}><T style={{fontSize:12,color:C.amber,flex:1}}>Connection interrupted. The agent’s view may be out of date.</T><Button label="Reconnect" kind="ghost" onPress={refresh}/></View>}
 <ScrollView key={path} keyboardShouldPersistTaps="handled" contentContainerStyle={{flexGrow:1}}><Slot/></ScrollView>
 {mobile&&path!=='/welcome'&&<View style={{flexDirection:'row',backgroundColor:C.bg,borderTopWidth:1,borderColor:C.line,paddingTop:9,paddingBottom:Math.max(inset.bottom,10)}}>{tabs.map(([u,l,i])=>tab(u,l,i))}</View>}
 {!!toast&&<View pointerEvents="none" style={{position:'absolute',left:20,right:20,bottom:mobile?90:20,alignItems:'center'}}><View style={{backgroundColor:'#163E32',borderWidth:1,borderColor:'#2D7158',borderRadius:12,padding:16}}><T style={{color:C.mint,fontSize:12}}>{toast}</T></View></View>}<ProductSheets/></View>;
}
